import sys.io.File;
import sys.FileSystem;

typedef Param = {n:String, t:String};
typedef Fn = {name:String, params:Array<Param>, ret:String};

class GenJNI
{
	static final SRC = "src/lime/_internal/backend/native/NativeCFFI.hx";
	static final OUT = "jni-gen/out";
	static final MARKER = "@:cffi private static function ";

	static final PRIMS:Map<String, Array<String>> = [
		"Int" => ["Int", "int", "jint", "0"],
		"Float" => ["Float", "double", "jdouble", "0"],
		"Float32" => ["Float", "double", "jdouble", "0"],
		"Bool" => ["Bool", "boolean", "jboolean", "0"],
		"String" => ["String", "String", "jstring", "nullptr"],
		"Void" => ["Void", "void", "void", ""],
	];

	static function map(t:String):Array<String>
	{
		t = StringTools.trim(t);
		return PRIMS.exists(t) ? PRIMS.get(t) : ["Dynamic", "Object", "jobject", "nullptr"];
	}

	static function main()
	{
		var src = File.getContent(SRC);
		var lines = src.split("\n");

		var raw:Array<String> = [];
		var buf:String = null;
		for (line in lines)
		{
			if (buf == null)
			{
				var idx = line.indexOf(MARKER);
				if (idx >= 0) buf = StringTools.trim(line.substr(idx + MARKER.length));
			}
			else
			{
				buf += " " + StringTools.trim(line);
			}
			if (buf != null && buf.indexOf(";") >= 0)
			{
				raw.push(buf.substr(0, buf.indexOf(";")));
				buf = null;
			}
		}

		var seen = new Map<String, Bool>();
		var fns:Array<{name:String, params:Array<{n:String, t:String}>, ret:String}> = [];
		for (decl in raw)
		{
			var p1 = decl.indexOf("(");
			var p2 = decl.lastIndexOf(")");
			if (p1 < 0 || p2 < 0) continue;
			var name = StringTools.trim(decl.substr(0, p1));
			if (seen.exists(name)) continue;
			seen.set(name, true);
			var paramStr = StringTools.trim(decl.substr(p1 + 1, p2 - p1 - 1));
			var ret = StringTools.trim(decl.substr(decl.indexOf(":", p2) + 1));
			var params = [];
			if (paramStr.length > 0)
			{
				for (part in paramStr.split(","))
				{
					var c = part.indexOf(":");
					params.push({n: StringTools.trim(part.substr(0, c)), t: StringTools.trim(part.substr(c + 1))});
				}
			}
			fns.push({name: name, params: params, ret: ret});
		}

		fns.sort((a, b) -> a.name < b.name ? -1 : 1);

		if (!FileSystem.exists(OUT)) FileSystem.createDirectory(OUT);
		var forwarders = genForwarders(fns);
		File.saveContent('$OUT/NativeCFFI.lime_jni.hx', forwarders);
		File.saveContent('$OUT/Lime.hx', genExtern(fns));
		File.saveContent('$OUT/Lime.java', genJava(fns));
		File.saveContent('$OUT/LimeJNI.cpp', genCpp(fns));
		File.saveContent('$OUT/LimeJNI_gl.cpp', genCppGL(fns));
		File.saveContent('$OUT/LimeJNI_cairo.cpp', genCppCairo(fns));

		Sys.println('Parsed ${fns.length} unique @:cffi functions.');
		Sys.println('Wrote $OUT/{NativeCFFI.lime_jni.hx, Lime.hx, Lime.java, LimeJNI.cpp}');

		if (fns.length > 800)
		{
			patchNativeCFFI(forwarders);
			Sys.println('Patched $SRC (#if lime_jni forwarder block, idempotent via sentinels).');
		}
		else
		{
			Sys.println('Refused to patch $SRC: only ${fns.length} functions parsed.');
		}
	}

	static final BEGIN = "\t//<<JNI_FORWARDERS_BEGIN>>";
	static final END = "\t//<<JNI_FORWARDERS_END>>";

	static function patchNativeCFFI(block:String)
	{
		var content = File.getContent(SRC);
		var wrapped = '$BEGIN (generated by jni-gen/GenJNI.hx — re-run to refresh; do not hand-edit)\n'
			+ "\t#if lime_jni\n" + block + "\t#end\n" + END + "\n";

		var bi = content.indexOf(BEGIN);
		if (bi >= 0)
		{
			var ei = content.indexOf(END);
			ei = content.indexOf("\n", ei) + 1;
			content = content.substr(0, bi) + wrapped + content.substr(ei);
		}
		else
		{
			var ci = content.indexOf("class NativeCFFI");
			var brace = content.indexOf("{", ci);
			var nl = content.indexOf("\n", brace) + 1;
			content = content.substr(0, nl) + wrapped + content.substr(nl);
		}

		content = StringTools.replace(content, "#if (cpp && !cppia)\n", "#if (cpp && !cppia && !lime_jni)\n");
		content = StringTools.replace(content, "#if (neko || cppia)\n", "#if ((neko || cppia) && !lime_jni)\n");
		content = StringTools.replace(content, "#if hl\n", "#if (hl && !lime_jni)\n");

		File.saveContent(SRC, content);
	}

	static function genForwarders(fns:Array<Fn>):String
	{
		var b = new StringBuf();
		b.add("\t// === AUTO-GENERATED by jni-gen/GenJNI.hx — do not edit by hand ===\n");
		b.add("\t// Forwarders to lime.jni.Lime (JNI). Signatures mirror the cpp @:cffi block\n");
		b.add("\t// so all backend call sites type-check. Non-primitives flow as Dynamic/Object.\n");
		for (f in fns)
		{
			var ps = [for (p in f.params) '${p.n}:${p.t}'].join(", ");
			var args = [for (p in f.params) p.n].join(", ");
			var call = 'lime.jni.Lime.${f.name}($args)';
			var body = (f.ret == "Void") ? '$call;' : (map(f.ret)[0] == "Dynamic" ? 'return cast $call;' : 'return $call;');
			b.add('\tpublic static inline function ${f.name}($ps):${f.ret} { $body }\n');
		}
		return b.toString();
	}

	static function externType(t:String):String return map(t)[0];

	static function genExtern(fns:Array<Fn>):String
	{
		var b = new StringBuf();
		b.add("package lime.jni;\n\n");
		b.add("// === AUTO-GENERATED by jni-gen/GenJNI.hx ===\n");
		b.add("// Haxe extern view of the hand-written Java class lime.jni.Lime (JNI natives).\n");
		b.add("@:native(\"lime.jni.Lime\")\n");
		b.add("extern class Lime\n{\n");
		for (f in fns)
		{
			var ps = [for (p in f.params) '${p.n}:${externType(p.t)}'].join(", ");
			b.add('\tstatic function ${f.name}($ps):${externType(f.ret)};\n');
		}
		b.add("}\n");
		return b.toString();
	}

	static function genJava(fns:Array<Fn>):String
	{
		var b = new StringBuf();
		b.add("package lime.jni;\n\n");
		b.add("// === AUTO-GENERATED by jni-gen/GenJNI.hx ===\n");
		b.add("// Hand-edit the implemented slice; the rest are stubs (UnsatisfiedLinkError only if called).\n");
		b.add("public class Lime {\n");
		b.add("\tstatic { System.loadLibrary(\"limejvm\"); }\n\n");
		for (f in fns)
		{
			var ps = [for (i in 0...f.params.length) '${map(f.params[i].t)[1]} ${f.params[i].n}'].join(", ");
			b.add('\tpublic static native ${map(f.ret)[1]} ${f.name}($ps);\n');
		}
		b.add("}\n");
		return b.toString();
	}

	static function mangle(name:String):String return StringTools.replace(name, "_", "_1");

	static function genCpp(fns:Array<Fn>):String
	{
		var b = new StringBuf();
		b.add("// === AUTO-GENERATED by jni-gen/GenJNI.hx ===\n");
		b.add("// JNI stubs. Replace the bodies of the implemented slice with real lime backend calls.\n");
		b.add("#include <jni.h>\n\n");
		b.add("extern \"C\" {\n\n");
		for (f in fns)
		{
			var jniArgs = [for (p in f.params) '${map(p.t)[2]} ${p.n}'];
			jniArgs.unshift("jclass cls");
			jniArgs.unshift("JNIEnv* env");
			var jret = map(f.ret)[2];
			var def = map(f.ret)[3];
			var ret = (jret == "void") ? "" : '\n\treturn ($jret)$def;';
			b.add('JNIEXPORT $jret JNICALL Java_lime_jni_Lime_${mangle(f.name)}(${jniArgs.join(", ")}) {$ret\n}\n\n');
		}
		b.add("} // extern \"C\"\n");
		return b.toString();
	}

	static function cppType(t:String):String
	{
		return switch (StringTools.trim(t))
		{
			case "Int": "int";
			case "Float32": "float";
			case "Float": "double";
			case "Bool": "bool";
			case "String": "HxString";
			case "Void": "void";
			default: "value"; // Dynamic, etc.
		};
	}

	static function isDataGL(f:Fn):Bool
	{
		for (p in f.params)
		{
			var t = StringTools.trim(p.t);
			if (t != "Int" && t != "Float32" && t != "Float" && t != "Bool" && t != "String") return true;
		}
		return false;
	}

	static function canDelegateGL(f:Fn):Bool
	{
		if (isDataGL(f)) return false;
		return switch (StringTools.trim(f.ret))
		{
			case "Void", "Int", "Float32", "Float", "Bool", "Dynamic": true;
			default: false;
		};
	}

	static function genCppGL(fns:Array<Fn>):String
	{
		var b = new StringBuf();
		b.add("// === AUTO-GENERATED by jni-gen/GenJNI.hx (GL slice) ===\n");
		b.add("// Scalar/string lime_gl_* delegate to lime's cpp bindings (OpenGLBindings.cpp).\n");
		b.add("// DataPointer/array fns are stubbed pending JVM typed-array marshaling.\n");
		b.add("#include <jni.h>\n#include <system/CFFI.h>\n\n");
		b.add("namespace lime {\n");
		for (f in fns)
		{
			if (!StringTools.startsWith(f.name, "lime_gl_") || !canDelegateGL(f)) continue;
			var cps = [for (p in f.params) cppType(p.t)].join(", ");
			b.add('\t${cppType(f.ret)} ${f.name}(${cps});\n');
		}
		b.add("}\n\nextern \"C\" {\n\n");
		for (f in fns)
		{
			if (!StringTools.startsWith(f.name, "lime_gl_")) continue;
			var jniArgs = [for (p in f.params) '${map(p.t)[2]} ${p.n}'];
			jniArgs.unshift("jclass cls");
			jniArgs.unshift("JNIEnv* env");
			var jret = map(f.ret)[2];
			var sig = 'JNIEXPORT $jret JNICALL Java_lime_jni_Lime_${mangle(f.name)}(${jniArgs.join(", ")})';

			if (!canDelegateGL(f))
			{
				var def = map(f.ret)[3];
				var r = (jret == "void") ? "" : '\n\treturn ($jret)$def;';
				b.add('$sig {$r\n}\n\n');
				continue;
			}

			var pre = new StringBuf();
			var post = new StringBuf();
			var callArgs = [];
			for (p in f.params)
			{
				switch (StringTools.trim(p.t))
				{
					case "Int", "Bool": callArgs.push(p.n);
					case "Float32": callArgs.push('(float)${p.n}');
					case "Float": callArgs.push('(double)${p.n}');
					case "String":
						pre.add('\tconst char* _s_${p.n} = ${p.n} ? env->GetStringUTFChars(${p.n}, 0) : 0;\n');
						callArgs.push('HxString(_s_${p.n})');
						post.add('\tif (_s_${p.n}) env->ReleaseStringUTFChars(${p.n}, _s_${p.n});\n');
					default: callArgs.push("0");
				}
			}
			var call = 'lime::${f.name}(${callArgs.join(", ")})';
			var body = new StringBuf();
			body.add("\n");
			body.add(pre.toString());
			if (jret == "void")
			{
				body.add('\t$call;\n');
				body.add(post.toString());
			}
			else if (StringTools.trim(f.ret) == "Dynamic")
			{
				body.add('\tvalue _r = $call;\n');
				body.add(post.toString());
				body.add('\treturn (_r && _r->kind == lime::LimeValue::STRING) ? env->NewStringUTF(_r->stringValue.c_str()) : 0;\n');
			}
			else if (post.length > 0)
			{
				body.add('\t$jret _r = ($jret)$call;\n');
				body.add(post.toString());
				body.add('\treturn _r;\n');
			}
			else
			{
				body.add('\treturn ($jret)$call;\n');
			}
			b.add('$sig {${body.toString()}}\n\n');
		}
		b.add("} // extern \"C\"\n");
		return b.toString();
	}

	static function cppTypeCairo(t:String):String
	{
		return switch (StringTools.trim(t))
		{
			case "Int": "int";
			case "Float": "double";
			case "Bool": "bool";
			case "String": "HxString";
			case "Void": "void";
			default: "value"; // CFFIPointer
		};
	}

	static function canGenCairo(f:Fn):Bool
	{
		for (p in f.params)
		{
			var t = StringTools.trim(p.t);
			if (t != "Int" && t != "Float" && t != "Bool" && t != "String" && t != "CFFIPointer") return false;
		}
		return switch (StringTools.trim(f.ret))
		{
			case "Int", "Float", "Bool", "String", "Void", "CFFIPointer": true;
			default: false; // DataPointer / Dynamic -> Phase 3
		};
	}

	static function genCppCairo(fns:Array<Fn>):String
	{
		var b = new StringBuf();
		b.add("// === AUTO-GENERATED by jni-gen/GenJNI.hx (Cairo slice) ===\n");
		b.add("// lime_cairo_* delegate to CairoBindings.cpp. Cairo objects (CFFIPointer) marshal via\n");
		b.add("// lime.jni.CFFIPointer (long ptr). DataPointer/Dynamic fns (surface data, fonts) are\n");
		b.add("// stubbed pending Phase 3 byte[] marshaling.\n");
		b.add("#include <jni.h>\n#include <stdint.h>\n#include <stdlib.h>\n#include <system/CFFI.h>\n");
		b.add("#include <cairo.h> // for the hand-implemented lime_cairo_show_glyphs (cairo_glyph_t/cairo_show_glyphs)\n\n");
		b.add("namespace lime {\n");
		for (f in fns)
		{
			if (!StringTools.startsWith(f.name, "lime_cairo_") || !canGenCairo(f)) continue;
			var cps = [for (p in f.params) cppTypeCairo(p.t)].join(", ");
			b.add('\t${cppTypeCairo(f.ret)} ${f.name}(${cps});\n');
		}
		b.add("}\n\nextern \"C\" {\n\n");
		b.add("// Unwrap a lime.jni.CFFIPointer to its native ptr (0 if null).\n");
		b.add("static void* cffiPtr(JNIEnv* env, jobject p) {\n");
		b.add("\tif (!p) return 0;\n");
		b.add("\tstatic jfieldID f = 0;\n");
		b.add("\tif (!f) { jclass c = env->FindClass(\"lime/jni/CFFIPointer\"); f = env->GetFieldID(c, \"ptr\", \"J\"); }\n");
		b.add("\treturn (void*)(intptr_t)env->GetLongField(p, f);\n");
		b.add("}\n");
		b.add("// Wrap a CairoBindings value (native ptr stashed in ->jobj) into a fresh Java CFFIPointer,\n");
		b.add("// then free the transient LimeValue wrapper. kind=0 => no auto-free yet (Phase 3 cleanup).\n");
		b.add("static jobject cffiOut(JNIEnv* env, value v) {\n");
		b.add("\tvoid* ptr = v ? v->jobj : 0; if (v) delete v;\n");
		b.add("\tif (!ptr) return 0;\n");
		b.add("\tstatic jclass cls = 0; static jmethodID ctor = 0;\n");
		b.add("\tif (!cls) { jclass c = env->FindClass(\"lime/jni/CFFIPointer\"); cls = (jclass)env->NewGlobalRef(c); ctor = env->GetMethodID(cls, \"<init>\", \"(JI)V\"); }\n");
		b.add("\treturn env->NewObject(cls, ctor, (jlong)(intptr_t)ptr, (jint)0);\n");
		b.add("}\n");
		b.add("static bool readCairoMatrix(JNIEnv* env, jobject mtx, cairo_matrix_t* out) {\n");
		b.add("\tif (!mtx) return false;\n");
		b.add("\tstatic jfieldID fa=0,fb=0,fc=0,fd=0,ftx=0,fty=0;\n");
		b.add("\tif (!fa) { jclass c = env->GetObjectClass(mtx); fa=env->GetFieldID(c,\"a\",\"D\"); fb=env->GetFieldID(c,\"b\",\"D\"); fc=env->GetFieldID(c,\"c\",\"D\"); fd=env->GetFieldID(c,\"d\",\"D\"); ftx=env->GetFieldID(c,\"tx\",\"D\"); fty=env->GetFieldID(c,\"ty\",\"D\"); env->DeleteLocalRef(c); }\n");
		b.add("\tif (!fa) return false;\n");
		b.add("\tout->xx=env->GetDoubleField(mtx,fa); out->yx=env->GetDoubleField(mtx,fb); out->xy=env->GetDoubleField(mtx,fc); out->yy=env->GetDoubleField(mtx,fd); out->x0=env->GetDoubleField(mtx,ftx); out->y0=env->GetDoubleField(mtx,fty);\n");
		b.add("\treturn true;\n");
		b.add("}\n\n");
		for (f in fns)
		{
			if (!StringTools.startsWith(f.name, "lime_cairo_")) continue;
			if (StringTools.endsWith(f.name, "_destroy"))
			{
				b.add('JNIEXPORT void JNICALL Java_lime_jni_Lime_${mangle(f.name)}(JNIEnv* env, jclass cls, jobject handle) {\n}\n\n');
				continue;
			}
			if (f.name == "lime_cairo_show_glyphs")
			{
				b.add("JNIEXPORT void JNICALL Java_lime_jni_Lime_lime_1cairo_1show_1glyphs(JNIEnv* env, jclass cls, jobject handle, jobject glyphs) {\n");
				b.add("\t// NOT a stub: the cpp lime_cairo_show_glyphs takes a hxcpp value array we cannot build from JNI, so\n");
				b.add("\t// read the Haxe Array<CairoGlyph> directly and call cairo_show_glyphs. CFFIPointer.ptr IS the cairo_t*.\n");
				b.add("\t// Powers the openfl CairoTextField non-show_text path; without it text is invisible.\n");
				b.add("\tcairo_t* cr = (cairo_t*)cffiPtr(env, handle);\n");
				b.add("\tif (!cr || !glyphs) return;\n");
				b.add("\tstatic jfieldID fLen = 0, fA = 0, gIdx = 0, gX = 0, gY = 0;\n");
				b.add("\tif (!fLen) { jclass ac = env->GetObjectClass(glyphs); fLen = env->GetFieldID(ac, \"length\", \"I\"); fA = env->GetFieldID(ac, \"__a\", \"[Ljava/lang/Object;\"); env->DeleteLocalRef(ac); }\n");
				b.add("\tint n = env->GetIntField(glyphs, fLen);\n");
				b.add("\tif (n <= 0) return;\n");
				b.add("\tjobjectArray a = (jobjectArray)env->GetObjectField(glyphs, fA);\n");
				b.add("\tif (!a) return;\n");
				b.add("\tcairo_glyph_t* cg = (cairo_glyph_t*)malloc(sizeof(cairo_glyph_t) * n);\n");
				b.add("\tint m = 0;\n");
				b.add("\tfor (int i = 0; i < n; i++) {\n");
				b.add("\t\tjobject g = env->GetObjectArrayElement(a, i);\n");
				b.add("\t\tif (!g) continue;\n");
				b.add("\t\tif (!gIdx) { jclass gc = env->GetObjectClass(g); gIdx = env->GetFieldID(gc, \"index\", \"I\"); gX = env->GetFieldID(gc, \"x\", \"D\"); gY = env->GetFieldID(gc, \"y\", \"D\"); env->DeleteLocalRef(gc); }\n");
				b.add("\t\tcg[m].index = (unsigned long)(unsigned int)env->GetIntField(g, gIdx);\n");
				b.add("\t\tcg[m].x = env->GetDoubleField(g, gX);\n");
				b.add("\t\tcg[m].y = env->GetDoubleField(g, gY);\n");
				b.add("\t\tm++;\n");
				b.add("\t\tenv->DeleteLocalRef(g);\n");
				b.add("\t}\n");
				b.add("\tif (m > 0) cairo_show_glyphs(cr, cg, m);\n");
				b.add("\tfree(cg);\n");
				b.add("}\n\n");
				continue;
			}
			if (f.name == "lime_cairo_ft_font_face_create")
			{
				b.add("JNIEXPORT jobject JNICALL Java_lime_jni_Lime_lime_1cairo_1ft_1font_1face_1create(JNIEnv* env, jclass cls, jobject face, jint flags) {\n");
				b.add("\t// RETAINS its value arg: CairoBindings stashes it (cairo_font_face_set_user_data) for the font face\n");
				b.add("\t// lifetime, so a STACK LimeValue would dangle and crash in set_font_size. Heap-allocate it (leaked).\n");
				b.add("\tvalue _v_face = new lime::LimeValue(lime::LimeValue::JOBJECT); _v_face->jobj = cffiPtr(env, face);\n");
				b.add("\tvalue _r = lime::lime_cairo_ft_font_face_create(_v_face, flags);\n");
				b.add("\treturn cffiOut(env, _r);\n");
				b.add("}\n\n");
				continue;
			}
			if (f.name == "lime_cairo_get_current_point")
			{
				b.add("JNIEXPORT jobject JNICALL Java_lime_jni_Lime_lime_1cairo_1get_1current_1point(JNIEnv* env, jclass cls, jobject handle) {\n");
				b.add("\t// NOT a stub: cairo current point -> lime.math.Vector2 (Dynamic return; GenJNI would stub it -> NPE in Cairo.get_currentPoint / quadraticCurveTo).\n");
				b.add("\tcairo_t* cr = (cairo_t*)cffiPtr(env, handle);\n");
				b.add("\tif (!cr) return 0;\n");
				b.add("\tdouble x = 0, y = 0;\n");
				b.add("\tif (cairo_has_current_point(cr)) cairo_get_current_point(cr, &x, &y);\n");
				b.add("\t// Vector2 ctor is (Ljava/lang/Double;Ljava/lang/Double;)V (Haxe boxes optional args), so AllocObject\n");
				b.add("\t// (no ctor) + set the public double x/y instead — avoids boxing + matches Haxe's EmptyConstructor path.\n");
				b.add("\tstatic jclass vc = 0; static jfieldID fx = 0, fy = 0;\n");
				b.add("\tif (!vc) { jclass lc = env->FindClass(\"lime/math/Vector2\"); if (!lc) { env->ExceptionClear(); return 0; } vc = (jclass)env->NewGlobalRef(lc); env->DeleteLocalRef(lc); fx = env->GetFieldID(vc, \"x\", \"D\"); fy = env->GetFieldID(vc, \"y\", \"D\"); }\n");
				b.add("\tjobject v = env->AllocObject(vc);\n");
				b.add("\tif (v && fx && fy) { env->SetDoubleField(v, fx, x); env->SetDoubleField(v, fy, y); }\n");
				b.add("\tif (env->ExceptionCheck()) env->ExceptionClear();\n");
				b.add("\treturn v;\n");
				b.add("}\n\n");
				continue;
			}
			if (f.name == "lime_cairo_pattern_get_matrix")
			{
				b.add("JNIEXPORT jobject JNICALL Java_lime_jni_Lime_lime_1cairo_1pattern_1get_1matrix(JNIEnv* env, jclass cls, jobject handle) {\n");
				b.add("\t// NOT a stub: cairo pattern matrix -> lime.jni.CairoMatrix POJO (Dynamic return; Matrix3 is a\n");
				b.add("\t// Float32Array abstract so `m.a` needs a real-field object). cairo {xx,yx,xy,yy,x0,y0}->{a,b,c,d,tx,ty}.\n");
				b.add("\tcairo_pattern_t* p = (cairo_pattern_t*)cffiPtr(env, handle);\n");
				b.add("\tif (!p) return 0;\n");
				b.add("\tcairo_matrix_t m; cairo_matrix_init_identity(&m); cairo_pattern_get_matrix(p, &m);\n");
				b.add("\tstatic jclass mc = 0; static jfieldID fa=0,fb=0,fc=0,fd=0,ftx=0,fty=0;\n");
				b.add("\tif (!mc) { jclass lc = env->FindClass(\"lime/jni/CairoMatrix\"); if (!lc) { env->ExceptionClear(); return 0; } mc = (jclass)env->NewGlobalRef(lc); env->DeleteLocalRef(lc); fa=env->GetFieldID(mc,\"a\",\"D\"); fb=env->GetFieldID(mc,\"b\",\"D\"); fc=env->GetFieldID(mc,\"c\",\"D\"); fd=env->GetFieldID(mc,\"d\",\"D\"); ftx=env->GetFieldID(mc,\"tx\",\"D\"); fty=env->GetFieldID(mc,\"ty\",\"D\"); }\n");
				b.add("\tjobject o = env->AllocObject(mc);\n");
				b.add("\tif (o) { env->SetDoubleField(o,fa,m.xx); env->SetDoubleField(o,fb,m.yx); env->SetDoubleField(o,fc,m.xy); env->SetDoubleField(o,fd,m.yy); env->SetDoubleField(o,ftx,m.x0); env->SetDoubleField(o,fty,m.y0); }\n");
				b.add("\tif (env->ExceptionCheck()) env->ExceptionClear();\n");
				b.add("\treturn o;\n");
				b.add("}\n\n");
				continue;
			}
			if (f.name == "lime_cairo_transform")
			{
				b.add("JNIEXPORT void JNICALL Java_lime_jni_Lime_lime_1cairo_1transform(JNIEnv* env, jclass cls, jobject handle, jobject matrix) {\n");
				b.add("\tcairo_t* cr = (cairo_t*)cffiPtr(env, handle); cairo_matrix_t m;\n");
				b.add("\tif (cr && readCairoMatrix(env, matrix, &m)) cairo_transform(cr, &m);\n");
				b.add("}\n\n");
				continue;
			}
			if (f.name == "lime_cairo_pattern_set_matrix")
			{
				b.add("JNIEXPORT void JNICALL Java_lime_jni_Lime_lime_1cairo_1pattern_1set_1matrix(JNIEnv* env, jclass cls, jobject handle, jobject matrix) {\n");
				b.add("\t// NOT a stub: position/scale the bitmap-fill pattern. Dynamic param -> GenJNI would stub it,\n");
				b.add("\t// leaving every image fill at identity (wrong position/size = garbled bitmaps).\n");
				b.add("\tcairo_pattern_t* p = (cairo_pattern_t*)cffiPtr(env, handle); cairo_matrix_t m;\n");
				b.add("\tif (p && readCairoMatrix(env, matrix, &m)) cairo_pattern_set_matrix(p, &m);\n");
				b.add("}\n\n");
				continue;
			}
			if (f.name == "lime_cairo_get_matrix")
			{
				b.add("JNIEXPORT jobject JNICALL Java_lime_jni_Lime_lime_1cairo_1get_1matrix(JNIEnv* env, jclass cls, jobject handle) {\n");
				b.add("\tcairo_t* cr = (cairo_t*)cffiPtr(env, handle);\n");
				b.add("\tif (!cr) return 0;\n");
				b.add("\tcairo_matrix_t m; cairo_get_matrix(cr, &m);\n");
				b.add("\tstatic jclass mc=0; static jfieldID ga=0,gb=0,gc=0,gd=0,gtx=0,gty=0;\n");
				b.add("\tif (!mc) { jclass lc=env->FindClass(\"lime/jni/CairoMatrix\"); if(!lc){env->ExceptionClear();return 0;} mc=(jclass)env->NewGlobalRef(lc); env->DeleteLocalRef(lc); ga=env->GetFieldID(mc,\"a\",\"D\"); gb=env->GetFieldID(mc,\"b\",\"D\"); gc=env->GetFieldID(mc,\"c\",\"D\"); gd=env->GetFieldID(mc,\"d\",\"D\"); gtx=env->GetFieldID(mc,\"tx\",\"D\"); gty=env->GetFieldID(mc,\"ty\",\"D\"); }\n");
				b.add("\tjobject o=env->AllocObject(mc);\n");
				b.add("\tif (o) { env->SetDoubleField(o,ga,m.xx); env->SetDoubleField(o,gb,m.yx); env->SetDoubleField(o,gc,m.xy); env->SetDoubleField(o,gd,m.yy); env->SetDoubleField(o,gtx,m.x0); env->SetDoubleField(o,gty,m.y0); }\n");
				b.add("\tif (env->ExceptionCheck()) env->ExceptionClear();\n");
				b.add("\treturn o;\n");
				b.add("}\n\n");
				continue;
			}
			var jniArgs = [for (p in f.params) '${map(p.t)[2]} ${p.n}'];
			jniArgs.unshift("jclass cls");
			jniArgs.unshift("JNIEnv* env");
			var jret = map(f.ret)[2];
			var sig = 'JNIEXPORT $jret JNICALL Java_lime_jni_Lime_${mangle(f.name)}(${jniArgs.join(", ")})';
			if (!canGenCairo(f))
			{
				var def = map(f.ret)[3];
				var r = (jret == "void") ? "" : '\n\treturn ($jret)$def;';
				b.add('$sig {$r\n}\n\n');
				continue;
			}
			var pre = new StringBuf();
			var post = new StringBuf();
			var callArgs = [];
			for (p in f.params)
			{
				switch (StringTools.trim(p.t))
				{
					case "Int", "Bool": callArgs.push(p.n);
					case "Float": callArgs.push('(double)${p.n}');
					case "String":
						pre.add('\tconst char* _s_${p.n} = ${p.n} ? env->GetStringUTFChars(${p.n}, 0) : 0;\n');
						callArgs.push('HxString(_s_${p.n})');
						post.add('\tif (_s_${p.n}) env->ReleaseStringUTFChars(${p.n}, _s_${p.n});\n');
					case "CFFIPointer":
						pre.add('\tlime::LimeValue _v_${p.n}(lime::LimeValue::JOBJECT); _v_${p.n}.jobj = cffiPtr(env, ${p.n});\n');
						callArgs.push('&_v_${p.n}');
					default: callArgs.push("0");
				}
			}
			var call = 'lime::${f.name}(${callArgs.join(", ")})';
			var rt = StringTools.trim(f.ret);
			var body = new StringBuf();
			body.add("\n");
			body.add(pre.toString());
			if (f.params.length > 0 && StringTools.trim(f.params[0].t) == "CFFIPointer")
			{
				body.add(jret == "void" ? '\tif (!_v_${f.params[0].n}.jobj) return;\n' : '\tif (!_v_${f.params[0].n}.jobj) return (${jret})${map(f.ret)[3]};\n');
			}
			if (jret == "void")
			{
				body.add('\t$call;\n');
				body.add(post.toString());
			}
			else if (rt == "CFFIPointer")
			{
				body.add('\tvalue _r = $call;\n');
				body.add(post.toString());
				body.add('\treturn cffiOut(env, _r);\n');
			}
			else if (rt == "String")
			{
				body.add('\tHxString _r = $call;\n');
				body.add(post.toString());
				body.add('\treturn _r.__s ? env->NewStringUTF(_r.__s) : (jstring)0;\n');
			}
			else if (post.length > 0)
			{
				body.add('\t$jret _r = ($jret)$call;\n');
				body.add(post.toString());
				body.add('\treturn _r;\n');
			}
			else
			{
				body.add('\treturn ($jret)$call;\n');
			}
			b.add('$sig {${body.toString()}}\n\n');
		}
		b.add("} // extern \"C\"\n");
		return b.toString();
	}

}
