package tjs._jso;

#if (wasmjs)
@:native("org.teavm.jso.webgl.WebGL2RenderingContext")
extern interface WebGL2RenderingContext extends WebGLRenderingContext {
	function copyBufferSubData(readTarget:Int, writeTarget:Int, readOffset:Int, writeOffset:Int, size:Int):Void;
	function getBufferSubData(target:Int, srcByteOffset:Int, dstData:ArrayBufferView):Void;
	function blitFramebuffer(srcX0:Int, srcY0:Int, srcX1:Int, srcY1:Int, dstX0:Int, dstY0:Int, dstX1:Int, dstY1:Int, mask:Int, filter:Int):Void;
	function framebufferTextureLayer(target:Int, attachment:Int, texture:WebGLTexture, level:Int, layer:Int):Void;
	function invalidateFramebuffer(target:Int, attachments:Int32Array):Void;
	function invalidateSubFramebuffer(target:Int, attachments:Int32Array, x:Int, y:Int, width:Int, height:Int):Void;
	function readBuffer(src:Int):Void;
	function getInternalformatParameter(target:Int, internalformat:Int, pname:Int):JSObject;
	function renderbufferStorageMultisample(target:Int, samples:Int, internalFormat:Int, width:Int, height:Int):Void;
	function texStorage2D(target:Int, levels:Int, internalformat:Int, width:Int, height:Int):Void;
	function texStorage3D(target:Int, levels:Int, internalformat:Int, width:Int, height:Int, depth:Int):Void;
	function texImage3D(target:Int, level:Int, internalformat:Int, width:Int, height:Int, depth:Int, border:Int, format:Int, type:Int, srcData:ArrayBufferView):Void;
	function texSubImage3D(target:Int, level:Int, xoffset:Int, yoffset:Int, zoffset:Int, width:Int, height:Int, depth:Int, format:Int, type:Int, srcData:ArrayBufferView):Void;
	function copyTexSubImage3D(target:Int, level:Int, xoffset:Int, yoffset:Int, zoffset:Int, x:Int, y:Int, width:Int, height:Int):Void;
	function compressedTexImage3D(target:Int, level:Int, internalformat:Int, width:Int, height:Int, depth:Int, border:Int, srcData:ArrayBufferView):Void;
	function compressedTexSubImage3D(target:Int, level:Int, xoffset:Int, yoffset:Int, zoffset:Int, width:Int, height:Int, depth:Int, format:Int, srcData:ArrayBufferView):Void;
	function getFragDataLocation(program:WebGLProgram, name:String):Int;
	function uniform1ui(location:WebGLUniformLocation, v0:Int):Void;
	function uniform2ui(location:WebGLUniformLocation, v0:Int, v1:Int):Void;
	function uniform3ui(location:WebGLUniformLocation, v0:Int, v1:Int, v2:Int):Void;
	function uniform4ui(location:WebGLUniformLocation, v0:Int, v1:Int, v2:Int, v3:Int):Void;
	function uniform1uiv(location:WebGLUniformLocation, data:Uint32Array):Void;
	function uniform2uiv(location:WebGLUniformLocation, data:Uint32Array):Void;
	function uniform3uiv(location:WebGLUniformLocation, data:Uint32Array):Void;
	function uniform4uiv(location:WebGLUniformLocation, data:Uint32Array):Void;
	function uniformMatrix2x3fv(location:WebGLUniformLocation, transpose:Bool, data:Float32Array):Void;
	function uniformMatrix3x2fv(location:WebGLUniformLocation, transpose:Bool, data:Float32Array):Void;
	function uniformMatrix2x4fv(location:WebGLUniformLocation, transpose:Bool, data:Float32Array):Void;
	function uniformMatrix4x2fv(location:WebGLUniformLocation, transpose:Bool, data:Float32Array):Void;
	function uniformMatrix3x4fv(location:WebGLUniformLocation, transpose:Bool, data:Float32Array):Void;
	function uniformMatrix4x3fv(location:WebGLUniformLocation, transpose:Bool, data:Float32Array):Void;
	function vertexAttribI4i(index:Int, v0:Int, v1:Int, v2:Int, v3:Int):Void;
	function vertexAttribI4iv(index:Int, value:Float32Array):Void;
	function vertexAttribI4ui(index:Int, v0:Int, v1:Int, v2:Int, v3:Int):Void;
	function vertexAttribI4uiv(index:Int, value:Uint32Array):Void;
	function vertexAttribIPointer(index:Int, size:Int, type:Int, stride:Int, offset:Int):Void;
	function vertexAttribDivisor(index:Int, divisor:Int):Void;
	function drawArraysInstanced(mode:Int, first:Int, count:Int, instanceCount:Int):Void;
	function drawElementsInstanced(mode:Int, count:Int, type:Int, offset:Int, instanceCount:Int):Void;
	function drawRangeElements(mode:Int, start:Int, end:Int, count:Int, type:Int, offset:Int):Void;
	function drawBuffers(buffers:Int32Array):Void;
	function clearBufferfv(buffer:Int, drawbuffer:Int, values:Float32Array):Void;
	function clearBufferiv(buffer:Int, drawbuffer:Int, values:Int32Array):Void;
	function clearBufferuiv(buffer:Int, drawbuffer:Int, values:Uint32Array):Void;
	function clearBufferfi(buffer:Int, drawbuffer:Int, depth:Single, stencil:Int):Void;
	function createQuery():WebGLQuery;
	function deleteQuery(query:WebGLQuery):Void;
	function isQuery(query:WebGLQuery):Bool;
	function beginQuery(target:Int, query:WebGLQuery):Void;
	function endQuery(target:Int):Void;
	function getQuery(target:Int, pname:Int):WebGLQuery;
	function getQueryParameter(query:WebGLQuery, pname:Int):JSObject;
	function createSampler():WebGLSampler;
	function deleteSampler(sampler:WebGLSampler):Void;
	function isSampler(sampler:WebGLSampler):Bool;
	function bindSampler(unit:Int, sampler:WebGLSampler):Void;
	function samplerParameteri(sampler:WebGLSampler, pname:Int, param:Int):Void;
	function samplerParameterf(sampler:WebGLSampler, pname:Int, param:Single):Void;
	function getSamplerParameter(sampler:WebGLSampler, pname:Int):JSObject;
	function fenceSync(condition:Int, flags:Int):WebGLSync;
	function isSync(sync:WebGLSync):Bool;
	function deleteSync(sync:WebGLSync):Void;
	function clientWaitSync(sync:WebGLSync, flags:Int, timeout:Int):Int;
	function waitSync(sync:WebGLSync, flags:Int, timeout:Int):Void;
	function getSyncParameter(sync:WebGLSync, pname:Int):JSObject;
	function createTransformFeedback():WebGLTransformFeedback;
	function deleteTransformFeedback(transformFeedback:WebGLTransformFeedback):Void;
	function isTransformFeedback(transformFeedback:WebGLTransformFeedback):Bool;
	function bindTransformFeedback(target:Int, transformFeedback:WebGLTransformFeedback):Void;
	function beginTransformFeedback(primitiveMode:Int):Void;
	function endTransformFeedback():Void;
	function transformFeedbackVaryings(program:WebGLProgram, varyings:java.NativeArray<String>, bufferMode:Int):Void;
	function getTransformFeedbackVarying(program:WebGLProgram, index:Int):WebGLActiveInfo;
	function pauseTransformFeedback():Void;
	function resumeTransformFeedback():Void;
	function bindBufferBase(target:Int, index:Int, buffer:WebGLBuffer):Void;
	function bindBufferRange(target:Int, index:Int, buffer:WebGLBuffer, offset:Int, size:Int):Void;
	function getIndexedParameter(target:Int, index:Int):JSObject;
	function getUniformIndices(program:WebGLProgram, uniformNames:java.NativeArray<String>):java.NativeArray<Int>;
	function getActiveUniforms(program:WebGLProgram, uniformIndices:java.NativeArray<Int>, pname:Int):JSObject;
	function getUniformBlockIndex(program:WebGLProgram, uniformBlockName:String):Int;
	function getActiveUniformBlockParameter(program:WebGLProgram, uniformBlockIndex:Int, pname:Int):JSObject;
	function getActiveUniformBlockName(program:WebGLProgram, uniformBlockIndex:Int):String;
	function uniformBlockBinding(program:WebGLProgram, uniformBlockIndex:Int, uniformBlockBinding:Int):Void;
	function createVertexArray():WebGLVertexArrayObject;
	function deleteVertexArray(vertexArray:WebGLVertexArrayObject):Void;
	function isVertexArray(vertexArray:WebGLVertexArrayObject):Bool;
	function bindVertexArray(vertexArray:WebGLVertexArrayObject):Void;
}
#end
