package tjs._jso;

#if (wasmjs)
@:native("org.teavm.jso.webgl.WebGLRenderingContext")
extern interface WebGLRenderingContext extends JSObject {
	function getCanvas():HTMLCanvasElement;
	function getDrawingBufferWidth():Int;
	function getDrawingBufferHeight():Int;
	function getContextAttributes():WebGLContextAttributes;
	function isContextLost():Bool;
	function getSupportedExtensionArray():java.NativeArray<String>;
	function getExtension(name:String):JSObject;
	function getParameter(pname:Int):JSObject;
	function getParameteri(pname:Int):Int;
	function getParameterString(pname:Int):String;
	function getParameterf(pname:Int):Single;
	function getError():Int;
	function getBufferParameter(target:Int, pname:Int):JSObject;
	function getFramebufferAttachmentParameter(target:Int, attachment:Int, pname:Int):JSObject;
	function getProgramParameter(program:WebGLProgram, pname:Int):JSObject;
	function getProgramInfoLog(program:WebGLProgram):String;
	function getRenderbufferParameter(target:Int, pname:Int):JSObject;
	function getShaderParameter(shader:WebGLShader, pname:Int):JSObject;
	function getShaderPrecisionFormat(shadertype:Int, precisiontype:Int):WebGLShaderPrecisionFormat;
	function getShaderInfoLog(shader:WebGLShader):String;
	function getShaderSource(shader:WebGLShader):String;
	function getTexParameter(target:Int, pname:Int):JSObject;
	function getUniform(program:WebGLProgram, location:WebGLUniformLocation):JSObject;
	function getUniformLocation(program:WebGLProgram, name:String):WebGLUniformLocation;
	function getVertexAttrib(index:Int, pname:Int):JSObject;
	function getVertexAttribOffset(index:Int, pname:Int):Int;
	function getActiveAttrib(program:WebGLProgram, index:Int):WebGLActiveInfo;
	function getActiveUniform(program:WebGLProgram, index:Int):WebGLActiveInfo;
	function getAttachedShadersArray(program:WebGLProgram):java.NativeArray<WebGLShader>;
	function getAttribLocation(program:WebGLProgram, name:String):Int;
	function activeTexture(texture:Int):Void;
	function attachShader(program:WebGLProgram, shader:WebGLShader):Void;
	function bindAttribLocation(program:WebGLProgram, index:Int, name:String):Void;
	function bindBuffer(target:Int, buffer:WebGLBuffer):Void;
	function bindFramebuffer(target:Int, framebuffer:WebGLFramebuffer):Void;
	function bindRenderbuffer(target:Int, renderbuffer:WebGLRenderbuffer):Void;
	function bindTexture(target:Int, texture:WebGLTexture):Void;
	function blendColor(red:Single, green:Single, blue:Single, alpha:Single):Void;
	function blendEquation(mode:Int):Void;
	function blendEquationSeparate(modeRGB:Int, modeAlpha:Int):Void;
	function blendFunc(sfactor:Int, dfactor:Int):Void;
	function blendFuncSeparate(srcRGB:Int, dstRGB:Int, srcAlpha:Int, dstAlpha:Int):Void;
	overload function bufferData(target:Int, data:ArrayBufferView, usage:Int):Void;
	overload function bufferData(target:Int, size:Int, usage:Int):Void;
	function bufferSubData(target:Int, offset:Int, data:ArrayBufferView):Void;
	function checkFramebufferStatus(target:Int):Int;
	function clear(mask:Int):Void;
	function clearColor(red:Single, green:Single, blue:Single, alpha:Single):Void;
	function clearDepth(depth:Single):Void;
	function clearStencil(s:Int):Void;
	function colorMask(red:Bool, green:Bool, blue:Bool, alpha:Bool):Void;
	function compileShader(shader:WebGLShader):Void;
	function compressedTexImage2D(target:Int, level:Int, internalformat:Int, width:Int, height:Int, border:Int, data:ArrayBufferView):Void;
	function compressedTexSubImage2D(target:Int, level:Int, xoffset:Int, yoffset:Int, width:Int, height:Int, format:Int, data:ArrayBufferView):Void;
	function copyTexImage2D(target:Int, level:Int, internalformat:Int, x:Int, y:Int, width:Int, height:Int, border:Int):Void;
	function copyTexSubImage2D(target:Int, level:Int, xoffset:Int, yoffset:Int, x:Int, y:Int, width:Int, height:Int):Void;
	function createBuffer():WebGLBuffer;
	function createFramebuffer():WebGLFramebuffer;
	function createProgram():WebGLProgram;
	function createRenderbuffer():WebGLRenderbuffer;
	function createShader(type:Int):WebGLShader;
	function createTexture():WebGLTexture;
	function cullFace(mode:Int):Void;
	function deleteBuffer(buffer:WebGLBuffer):Void;
	function deleteFramebuffer(framebuffer:WebGLFramebuffer):Void;
	function deleteProgram(program:WebGLProgram):Void;
	function deleteRenderbuffer(renderbuffer:WebGLRenderbuffer):Void;
	function deleteShader(shader:WebGLShader):Void;
	function deleteTexture(texture:WebGLTexture):Void;
	function depthFunc(func:Int):Void;
	function depthMask(flag:Bool):Void;
	function depthRange(zNear:Single, zFar:Single):Void;
	function detachShader(program:WebGLProgram, shader:WebGLShader):Void;
	function disable(cap:Int):Void;
	function disableVertexAttribArray(index:Int):Void;
	function drawArrays(mode:Int, first:Int, count:Int):Void;
	function drawElements(mode:Int, count:Int, type:Int, offset:Int):Void;
	function enable(cap:Int):Void;
	function enableVertexAttribArray(index:Int):Void;
	function finish():Void;
	function flush():Void;
	function framebufferRenderbuffer(target:Int, attachment:Int, renderbuffertarget:Int, renderbuffer:WebGLRenderbuffer):Void;
	function framebufferTexture2D(target:Int, attachment:Int, textarget:Int, texture:WebGLTexture, level:Int):Void;
	function frontFace(mode:Int):Void;
	function generateMipmap(target:Int):Void;
	function hint(target:Int, mode:Int):Void;
	function isBuffer(buffer:WebGLBuffer):Bool;
	function isEnabled(cap:Int):Bool;
	function isFramebuffer(framebuffer:WebGLFramebuffer):Bool;
	function isProgram(program:WebGLProgram):Bool;
	function isRenderbuffer(renderbuffer:WebGLRenderbuffer):Bool;
	function isShader(shader:WebGLShader):Bool;
	function isTexture(texture:WebGLTexture):Bool;
	function lineWidth(width:Single):Void;
	function linkProgram(program:WebGLProgram):Void;
	function pixelStorei(pname:Int, param:Int):Void;
	function polygonOffset(factor:Single, units:Single):Void;
	function readPixels(x:Int, y:Int, width:Int, height:Int, format:Int, type:Int, pixels:ArrayBufferView):Void;
	function renderbufferStorage(target:Int, internalformat:Int, width:Int, height:Int):Void;
	function sampleCoverage(value:Single, invert:Bool):Void;
	function scissor(x:Int, y:Int, width:Int, height:Int):Void;
	function shaderSource(shader:WebGLShader, source:String):Void;
	function stencilFunc(func:Int, ref:Int, mask:Int):Void;
	function stencilFuncSeparate(face:Int, func:Int, ref:Int, mask:Int):Void;
	function stencilMask(mask:Int):Void;
	function stencilMaskSeparate(face:Int, mask:Int):Void;
	function stencilOp(fail:Int, zfail:Int, zpass:Int):Void;
	function stencilOpSeparate(face:Int, fail:Int, zfail:Int, zpass:Int):Void;
	overload function texImage2D(target:Int, level:Int, internalformat:Int, width:Int, height:Int, border:Int, format:Int, type:Int, pixels:ArrayBufferView):Void;
	overload function texImage2D(target:Int, level:Int, internalformat:Int, format:Int, type:Int, image:HTMLImageElement):Void;
	overload function texImage2D(target:Int, level:Int, internalformat:Int, format:Int, type:Int, canvas:HTMLCanvasElement):Void;
	overload function texImage2D(target:Int, level:Int, internalformat:Int, format:Int, type:Int, data:ImageData):Void;
	function texParameterf(target:Int, pname:Int, param:Single):Void;
	function texParameteri(target:Int, pname:Int, param:Int):Void;
	function texSubImage2D(target:Int, level:Int, xoffset:Int, yoffset:Int, width:Int, height:Int, format:Int, type:Int, pixels:ArrayBufferView):Void;
	function uniform1f(location:WebGLUniformLocation, x:Single):Void;
	function uniform1fv(location:WebGLUniformLocation, data:Float32Array):Void;
	function uniform1i(location:WebGLUniformLocation, x:Int):Void;
	function uniform1iv(location:WebGLUniformLocation, data:Int32Array):Void;
	function uniform2f(location:WebGLUniformLocation, x:Single, y:Single):Void;
	function uniform2fv(location:WebGLUniformLocation, data:Float32Array):Void;
	function uniform2i(location:WebGLUniformLocation, x:Int, y:Int):Void;
	function uniform2iv(location:WebGLUniformLocation, data:Int32Array):Void;
	function uniform3f(location:WebGLUniformLocation, x:Single, y:Single, z:Single):Void;
	function uniform3fv(location:WebGLUniformLocation, data:Float32Array):Void;
	function uniform3i(location:WebGLUniformLocation, x:Int, y:Int, z:Int):Void;
	function uniform3iv(location:WebGLUniformLocation, data:Int32Array):Void;
	function uniform4f(location:WebGLUniformLocation, x:Single, y:Single, z:Single, w:Single):Void;
	function uniform4fv(location:WebGLUniformLocation, data:Float32Array):Void;
	function uniform4i(location:WebGLUniformLocation, x:Int, y:Int, z:Int, w:Int):Void;
	function uniform4iv(location:WebGLUniformLocation, data:Int32Array):Void;
	function uniformMatrix2fv(location:WebGLUniformLocation, transpose:Bool, data:Float32Array):Void;
	function uniformMatrix3fv(location:WebGLUniformLocation, transpose:Bool, data:Float32Array):Void;
	function uniformMatrix4fv(location:WebGLUniformLocation, transpose:Bool, data:Float32Array):Void;
	function useProgram(program:WebGLProgram):Void;
	function validateProgram(program:WebGLProgram):Void;
	function vertexAttrib1f(indx:Int, x:Single):Void;
	function vertexAttrib1fv(indx:Int, values:Float32Array):Void;
	function vertexAttrib2f(indx:Int, x:Single, y:Single):Void;
	function vertexAttrib2fv(indx:Int, values:Float32Array):Void;
	function vertexAttrib3f(indx:Int, x:Single, y:Single, z:Single):Void;
	function vertexAttrib3fv(indx:Int, values:Float32Array):Void;
	function vertexAttrib4f(indx:Int, x:Single, y:Single, z:Single, w:Single):Void;
	function vertexAttrib4fv(indx:Int, values:Float32Array):Void;
	function vertexAttribPointer(indx:Int, size:Int, type:Int, normalized:Bool, stride:Int, offset:Int):Void;
	function viewport(x:Int, y:Int, width:Int, height:Int):Void;
}
#end
