package lime.jni;

public class Lime {
	static { System.loadLibrary("limejvm"); }

	public static native void lime_cffi_release(long ptr, int kind);

	public static native void lime_gl_buffer_data_jvm(int target, int size, byte[] data, int offset, int usage);
	public static native void lime_gl_buffer_sub_data_jvm(int target, int dstByteOffset, int size, byte[] data, int offset);
	public static native void lime_gl_tex_image_2d_jvm(int target, int level, int internalformat, int width, int height, int border, int format, int type, byte[] data, int offset);
	public static native void lime_gl_uniform_jvm(int kind, int location, int count, boolean transpose, byte[] data, int offset);

	public static native Object lime_cairo_image_surface_create_for_data_jvm(byte[] data, int offset, int format, int width, int height, int stride);

	public static native byte[] lime_hb_buffer_get_glyph_infos_jvm(Object buffer);
	public static native byte[] lime_hb_buffer_get_glyph_positions_jvm(Object buffer);

	public static native Object lime_font_load_bytes_jvm(byte[] data, int length);
	public static native void lime_cairo_show_glyphs_jvm(Object handle, byte[] glyphs, int count);
	public static native double lime_cairo_get_current_point_d(Object handle, int i);
	public static native double lime_cairo_get_matrix_d(Object handle, int i);
	public static native double lime_cairo_pattern_get_matrix_d(Object handle, int i);
	public static native void lime_cairo_transform_flat(Object handle, double a, double b, double c, double d, double tx, double ty);
	public static native void lime_cairo_pattern_set_matrix_flat(Object handle, double a, double b, double c, double d, double tx, double ty);
	public static native byte[] lime_teavm_sync_fetch(String url);

	public static native void lime_al_auxf(Object aux, int param, double value);
	public static native void lime_al_auxfv(Object aux, int param, Object values);
	public static native void lime_al_auxi(Object aux, int param, Object value);
	public static native void lime_al_auxiv(Object aux, int param, Object values);
	public static native void lime_al_buffer3f(Object buffer, int param, double value1, double value2, double value3);
	public static native void lime_al_buffer3i(Object buffer, int param, int value1, int value2, int value3);
	public static native void lime_al_buffer_data(Object buffer, int format, Object data, int size, int freq);
	public static native void lime_al_bufferf(Object buffer, int param, double value);
	public static native void lime_al_bufferfv(Object buffer, int param, Object values);
	public static native void lime_al_bufferi(Object buffer, int param, int value);
	public static native void lime_al_bufferiv(Object buffer, int param, Object values);
	public static native void lime_al_cleanup();
	public static native void lime_al_delete_buffer(Object buffer);
	public static native void lime_al_delete_buffers(int n, Object buffers);
	public static native void lime_al_delete_source(Object source);
	public static native void lime_al_delete_sources(int n, Object sources);
	public static native void lime_al_disable(int capability);
	public static native void lime_al_distance_model(int distanceModel);
	public static native void lime_al_doppler_factor(double value);
	public static native void lime_al_doppler_velocity(double value);
	public static native void lime_al_effectf(Object effect, int param, double value);
	public static native void lime_al_effectfv(Object effect, int param, Object values);
	public static native void lime_al_effecti(Object effect, int param, int value);
	public static native void lime_al_effectiv(Object effect, int param, Object values);
	public static native void lime_al_enable(int capability);
	public static native void lime_al_filterf(Object filter, int param, double value);
	public static native void lime_al_filteri(Object filter, int param, Object value);
	public static native Object lime_al_gen_aux();
	public static native Object lime_al_gen_buffer();
	public static native Object lime_al_gen_buffers(int n);
	public static native Object lime_al_gen_effect();
	public static native Object lime_al_gen_filter();
	public static native Object lime_al_gen_source();
	public static native Object lime_al_gen_sources(int n);
	public static native boolean lime_al_get_boolean(int param);
	public static native Object lime_al_get_booleanv(int param, int count);
	public static native Object lime_al_get_buffer3f(Object buffer, int param);
	public static native Object lime_al_get_buffer3i(Object buffer, int param);
	public static native double lime_al_get_bufferf(Object buffer, int param);
	public static native Object lime_al_get_bufferfv(Object buffer, int param, int count);
	public static native int lime_al_get_bufferi(Object buffer, int param);
	public static native Object lime_al_get_bufferiv(Object buffer, int param, int count);
	public static native double lime_al_get_double(int param);
	public static native Object lime_al_get_doublev(int param, int count);
	public static native int lime_al_get_enum_value(String ename);
	public static native int lime_al_get_error();
	public static native int lime_al_get_filteri(Object filter, int param);
	public static native double lime_al_get_float(int param);
	public static native Object lime_al_get_floatv(int param, int count);
	public static native int lime_al_get_integer(int param);
	public static native Object lime_al_get_integerv(int param, int count);
	public static native Object lime_al_get_listener3f(int param);
	public static native Object lime_al_get_listener3i(int param);
	public static native double lime_al_get_listenerf(int param);
	public static native Object lime_al_get_listenerfv(int param, int count);
	public static native int lime_al_get_listeneri(int param);
	public static native Object lime_al_get_listeneriv(int param, int count);
	public static native double lime_al_get_proc_address(String fname);
	public static native Object lime_al_get_source3f(Object source, int param);
	public static native Object lime_al_get_source3i(Object source, int param);
	public static native double lime_al_get_sourcef(Object source, int param);
	public static native Object lime_al_get_sourcefv(Object source, int param, int count);
	public static native Object lime_al_get_sourcei(Object source, int param);
	public static native Object lime_al_get_sourceiv(Object source, int param, int count);
	public static native Object lime_al_get_string(int param);
	public static native boolean lime_al_is_aux(Object aux);
	public static native boolean lime_al_is_buffer(Object buffer);
	public static native boolean lime_al_is_effect(Object effect);
	public static native boolean lime_al_is_enabled(int capability);
	public static native boolean lime_al_is_extension_present(String extname);
	public static native boolean lime_al_is_filter(Object filter);
	public static native boolean lime_al_is_source(Object source);
	public static native void lime_al_listener3f(int param, double value1, double value2, double value3);
	public static native void lime_al_listener3i(int param, int value1, int value2, int value3);
	public static native void lime_al_listenerf(int param, double value1);
	public static native void lime_al_listenerfv(int param, Object values);
	public static native void lime_al_listeneri(int param, int value1);
	public static native void lime_al_listeneriv(int param, Object values);
	public static native void lime_al_remove_direct_filter(Object source);
	public static native void lime_al_remove_send(Object source, int index);
	public static native void lime_al_source3f(Object source, int param, double value1, double value2, double value3);
	public static native void lime_al_source3i(Object source, int param, Object value1, int value2, int value3);
	public static native void lime_al_source_pause(Object source);
	public static native void lime_al_source_pausev(int n, Object sources);
	public static native void lime_al_source_play(Object source);
	public static native void lime_al_source_playv(int n, Object sources);
	public static native void lime_al_source_queue_buffers(Object source, int nb, Object buffers);
	public static native void lime_al_source_rewind(Object source);
	public static native void lime_al_source_rewindv(int n, Object sources);
	public static native void lime_al_source_stop(Object source);
	public static native void lime_al_source_stopv(int n, Object sources);
	public static native Object lime_al_source_unqueue_buffers(Object source, int nb);
	public static native void lime_al_sourcef(Object source, int param, double value);
	public static native void lime_al_sourcefv(Object source, int param, Object values);
	public static native void lime_al_sourcei(Object source, int param, Object value);
	public static native void lime_al_sourceiv(Object source, int param, Object values);
	public static native void lime_al_speed_of_sound(double speed);
	public static native boolean lime_alc_close_device(Object device);
	public static native Object lime_alc_create_context(Object device, Object attrlist);
	public static native void lime_alc_destroy_context(Object context);
	public static native Object lime_alc_get_contexts_device(Object context);
	public static native Object lime_alc_get_current_context();
	public static native int lime_alc_get_error(Object device);
	public static native Object lime_alc_get_integerv(Object device, int param, int size);
	public static native Object lime_alc_get_string(Object device, int param);
	public static native boolean lime_alc_make_context_current(Object context);
	public static native Object lime_alc_open_device(String devicename);
	public static native void lime_alc_pause_device(Object device);
	public static native void lime_alc_process_context(Object context);
	public static native void lime_alc_resume_device(Object device);
	public static native void lime_alc_suspend_context(Object context);
	public static native Object lime_application_create();
	public static native void lime_application_event_manager_register(Object callback, Object eventObject);
	public static native int lime_application_exec(Object handle);
	public static native void lime_application_init(Object handle);
	public static native int lime_application_quit(Object handle);
	public static native void lime_application_set_frame_rate(Object handle, double value);
	public static native void lime_application_set_main_loop(Object handle, int profile, double frameRate, int timePrecision, int busyWait, int uncapMode);
	public static native void lime_application_set_vsync_mode(Object handle, int value);
	public static native boolean lime_application_update(Object handle);
	public static native Object lime_audio_load(Object data, Object buffer);
	public static native Object lime_audio_load_bytes(Object data, Object buffer);
	public static native Object lime_audio_load_file(Object path, Object buffer);
	public static native Object lime_bytes_from_data_pointer(double data, int length, Object bytes);
	public static native double lime_bytes_get_data_pointer(Object data);
	public static native double lime_bytes_get_data_pointer_offset(Object data, int offset);
	public static native Object lime_bytes_read_file(String path, Object bytes);
	public static native void lime_cairo_arc(Object handle, double xc, double yc, double radius, double angle1, double angle2);
	public static native void lime_cairo_arc_negative(Object handle, double xc, double yc, double radius, double angle1, double angle2);
	public static native void lime_cairo_clip(Object handle);
	public static native void lime_cairo_clip_extents(Object handle, double x1, double y1, double x2, double y2);
	public static native void lime_cairo_clip_preserve(Object handle);
	public static native void lime_cairo_close_path(Object handle);
	public static native void lime_cairo_copy_page(Object handle);
	public static native Object lime_cairo_create(Object handle);
	public static native void lime_cairo_curve_to(Object handle, double x1, double y1, double x2, double y2, double x3, double y3);
	public static native void lime_cairo_fill(Object handle);
	public static native void lime_cairo_fill_extents(Object handle, double x1, double y1, double x2, double y2);
	public static native void lime_cairo_fill_preserve(Object handle);
	public static native int lime_cairo_font_face_status(Object handle);
	public static native Object lime_cairo_font_options_create();
	public static native int lime_cairo_font_options_get_antialias(Object handle);
	public static native int lime_cairo_font_options_get_hint_metrics(Object handle);
	public static native int lime_cairo_font_options_get_hint_style(Object handle);
	public static native int lime_cairo_font_options_get_subpixel_order(Object handle);
	public static native void lime_cairo_font_options_set_antialias(Object handle, int v);
	public static native void lime_cairo_font_options_set_hint_metrics(Object handle, int v);
	public static native void lime_cairo_font_options_set_hint_style(Object handle, int v);
	public static native void lime_cairo_font_options_set_subpixel_order(Object handle, int v);
	public static native Object lime_cairo_ft_font_face_create(Object face, int flags);
	public static native int lime_cairo_get_antialias(Object handle);
	public static native Object lime_cairo_get_current_point(Object handle);
	public static native Object lime_cairo_get_dash(Object handle);
	public static native int lime_cairo_get_dash_count(Object handle);
	public static native int lime_cairo_get_fill_rule(Object handle);
	public static native Object lime_cairo_get_font_face(Object handle);
	public static native Object lime_cairo_get_font_options(Object handle);
	public static native Object lime_cairo_get_group_target(Object handle);
	public static native int lime_cairo_get_line_cap(Object handle);
	public static native int lime_cairo_get_line_join(Object handle);
	public static native double lime_cairo_get_line_width(Object handle);
	public static native Object lime_cairo_get_matrix(Object handle);
	public static native double lime_cairo_get_miter_limit(Object handle);
	public static native int lime_cairo_get_operator(Object handle);
	public static native Object lime_cairo_get_source(Object handle);
	public static native Object lime_cairo_get_target(Object handle);
	public static native double lime_cairo_get_tolerance(Object handle);
	public static native boolean lime_cairo_has_current_point(Object handle);
	public static native void lime_cairo_identity_matrix(Object handle);
	public static native Object lime_cairo_image_surface_create(int format, int width, int height);
	public static native Object lime_cairo_image_surface_create_for_data(Object data, int format, int width, int height, int stride);
	public static native Object lime_cairo_image_surface_get_data(Object handle);
	public static native int lime_cairo_image_surface_get_format(Object handle);
	public static native int lime_cairo_image_surface_get_height(Object handle);
	public static native int lime_cairo_image_surface_get_stride(Object handle);
	public static native int lime_cairo_image_surface_get_width(Object handle);
	public static native boolean lime_cairo_in_clip(Object handle, double x, double y);
	public static native boolean lime_cairo_in_fill(Object handle, double x, double y);
	public static native boolean lime_cairo_in_stroke(Object handle, double x, double y);
	public static native void lime_cairo_line_to(Object handle, double x, double y);
	public static native void lime_cairo_mask(Object handle, Object pattern);
	public static native void lime_cairo_mask_surface(Object handle, Object surface, double x, double y);
	public static native void lime_cairo_move_to(Object handle, double x, double y);
	public static native void lime_cairo_new_path(Object handle);
	public static native void lime_cairo_paint(Object handle);
	public static native void lime_cairo_paint_with_alpha(Object handle, double alpha);
	public static native void lime_cairo_pattern_add_color_stop_rgb(Object handle, double offset, double red, double green, double blue);
	public static native void lime_cairo_pattern_add_color_stop_rgba(Object handle, double offset, double red, double green, double blue, double alpha);
	public static native Object lime_cairo_pattern_create_for_surface(Object surface);
	public static native Object lime_cairo_pattern_create_linear(double x0, double y0, double x1, double y1);
	public static native Object lime_cairo_pattern_create_radial(double cx0, double cy0, double radius0, double cx1, double cy1, double radius1);
	public static native Object lime_cairo_pattern_create_rgb(double r, double g, double b);
	public static native Object lime_cairo_pattern_create_rgba(double r, double g, double b, double a);
	public static native int lime_cairo_pattern_get_color_stop_count(Object handle);
	public static native int lime_cairo_pattern_get_extend(Object handle);
	public static native int lime_cairo_pattern_get_filter(Object handle);
	public static native Object lime_cairo_pattern_get_matrix(Object handle);
	public static native void lime_cairo_pattern_set_extend(Object handle, int extend);
	public static native void lime_cairo_pattern_set_filter(Object handle, int filter);
	public static native void lime_cairo_pattern_set_matrix(Object handle, Object matrix);
	public static native Object lime_cairo_pop_group(Object handle);
	public static native void lime_cairo_pop_group_to_source(Object handle);
	public static native void lime_cairo_push_group(Object handle);
	public static native void lime_cairo_push_group_with_content(Object handle, int content);
	public static native void lime_cairo_rectangle(Object handle, double x, double y, double width, double height);
	public static native void lime_cairo_rel_curve_to(Object handle, double dx1, double dy1, double dx2, double dy2, double dx3, double dy3);
	public static native void lime_cairo_rel_line_to(Object handle, double dx, double dy);
	public static native void lime_cairo_rel_move_to(Object handle, double dx, double dy);
	public static native void lime_cairo_reset_clip(Object handle);
	public static native void lime_cairo_restore(Object handle);
	public static native void lime_cairo_rotate(Object handle, double amount);
	public static native void lime_cairo_save(Object handle);
	public static native void lime_cairo_scale(Object handle, double x, double y);
	public static native void lime_cairo_set_antialias(Object handle, int cap);
	public static native void lime_cairo_set_dash(Object handle, Object dash);
	public static native void lime_cairo_set_fill_rule(Object handle, int cap);
	public static native void lime_cairo_set_font_face(Object handle, Object face);
	public static native void lime_cairo_set_font_options(Object handle, Object options);
	public static native void lime_cairo_set_font_size(Object handle, double size);
	public static native void lime_cairo_set_line_cap(Object handle, int cap);
	public static native void lime_cairo_set_line_join(Object handle, int join);
	public static native void lime_cairo_set_line_width(Object handle, double width);
	public static native void lime_cairo_set_matrix(Object handle, double a, double b, double c, double d, double tx, double ty);
	public static native void lime_cairo_set_miter_limit(Object handle, double miterLimit);
	public static native void lime_cairo_set_operator(Object handle, int op);
	public static native void lime_cairo_set_source(Object handle, Object pattern);
	public static native void lime_cairo_set_source_rgb(Object handle, double r, double g, double b);
	public static native void lime_cairo_set_source_rgba(Object handle, double r, double g, double b, double a);
	public static native void lime_cairo_set_source_surface(Object handle, Object surface, double x, double y);
	public static native void lime_cairo_set_tolerance(Object handle, double tolerance);
	public static native void lime_cairo_show_glyphs(Object handle, Object glyphs);
	public static native void lime_cairo_show_page(Object handle);
	public static native void lime_cairo_show_text(Object handle, String text);
	public static native int lime_cairo_status(Object handle);
	public static native void lime_cairo_stroke(Object handle);
	public static native void lime_cairo_stroke_extents(Object handle, double x1, double y1, double x2, double y2);
	public static native void lime_cairo_stroke_preserve(Object handle);
	public static native void lime_cairo_surface_flush(Object surface);
	public static native void lime_cairo_text_path(Object handle, String text);
	public static native void lime_cairo_transform(Object handle, Object matrix);
	public static native void lime_cairo_translate(Object handle, double x, double y);
	public static native int lime_cairo_version();
	public static native String lime_cairo_version_string();
	public static native double lime_cffi_get_native_pointer(Object ptr);
	public static native void lime_clipboard_event_manager_register(Object callback, Object eventObject);
	public static native Object lime_clipboard_get_text();
	public static native void lime_clipboard_set_text(String text);
	public static native void lime_curl_easy_cleanup(Object handle);
	public static native Object lime_curl_easy_duphandle(Object handle);
	public static native Object lime_curl_easy_escape(Object curl, String url, int length);
	public static native void lime_curl_easy_flush(Object curl);
	public static native Object lime_curl_easy_getinfo(Object curl, int info);
	public static native Object lime_curl_easy_init();
	public static native int lime_curl_easy_pause(Object handle, int bitmask);
	public static native int lime_curl_easy_perform(Object easy_handle);
	public static native int lime_curl_easy_recv(Object curl, Object buffer, int buflen, int n);
	public static native void lime_curl_easy_reset(Object curl);
	public static native int lime_curl_easy_send(Object curl, Object buffer, int buflen, int n);
	public static native int lime_curl_easy_setopt(Object handle, int option, Object parameter, Object writeBytes);
	public static native Object lime_curl_easy_strerror(int errornum);
	public static native Object lime_curl_easy_unescape(Object curl, String url, int inlength, int outlength);
	public static native double lime_curl_getdate(String date, double now);
	public static native void lime_curl_global_cleanup();
	public static native int lime_curl_global_init(int flags);
	public static native int lime_curl_multi_add_handle(Object multi_handle, Object curl_object, Object curl_handle);
	public static native int lime_curl_multi_get_running_handles(Object multi_handle);
	public static native Object lime_curl_multi_info_read(Object multi_handle);
	public static native Object lime_curl_multi_init();
	public static native int lime_curl_multi_perform(Object multi_handle);
	public static native int lime_curl_multi_remove_handle(Object multi_handle, Object curl_handle);
	public static native int lime_curl_multi_setopt(Object multi_handle, int option, Object parameter);
	public static native int lime_curl_multi_wait(Object multi_handle, int timeout_ms);
	public static native Object lime_curl_version();
	public static native Object lime_curl_version_info(int type);
	public static native double lime_data_pointer_offset(Object dataPointer, int offset);
	public static native Object lime_deflate_compress(Object data, Object bytes);
	public static native Object lime_deflate_decompress(Object data, Object bytes);
	public static native void lime_drop_event_manager_register(Object callback, Object eventObject);
	public static native Object lime_file_dialog_open_directory(String title, String filter, String defaultPath);
	public static native Object lime_file_dialog_open_file(String title, String filter, String defaultPath);
	public static native Object lime_file_dialog_open_files(String title, String filter, String defaultPath);
	public static native Object lime_file_dialog_save_file(String title, String filter, String defaultPath);
	public static native Object lime_file_watcher_add_directory(Object handle, Object path, boolean recursive);
	public static native Object lime_file_watcher_create(Object callback);
	public static native void lime_file_watcher_remove_directory(Object handle, Object watchID);
	public static native void lime_file_watcher_update(Object handle);
	public static native int lime_font_get_ascender(Object handle);
	public static native int lime_font_get_descender(Object handle);
	public static native Object lime_font_get_family_name(Object handle);
	public static native int lime_font_get_glyph_index(Object handle, String character);
	public static native Object lime_font_get_glyph_indices(Object handle, String characters);
	public static native Object lime_font_get_glyph_metrics(Object handle, int index);
	public static native int lime_font_get_height(Object handle);
	public static native int lime_font_get_num_glyphs(Object handle);
	public static native int lime_font_get_strikethrough_position(Object handle);
	public static native int lime_font_get_strikethrough_thickness(Object handle);
	public static native int lime_font_get_underline_position(Object handle);
	public static native int lime_font_get_underline_thickness(Object handle);
	public static native int lime_font_get_units_per_em(Object handle);
	public static native Object lime_font_load(Object data);
	public static native Object lime_font_load_bytes(Object data);
	public static native Object lime_font_load_file(Object path);
	public static native Object lime_font_outline_decompose(Object handle, int size);
	public static native Object lime_font_outline_decompose_no_hint(Object handle, int size);
	public static native Object lime_font_render_glyph(Object handle, int index, Object data);
	public static native Object lime_font_render_glyph_with_flags(Object handle, int index, int loadFlags, Object data);
	public static native Object lime_font_render_glyphs(Object handle, Object indices, Object data);
	public static native void lime_font_set_size(Object handle, int size, int dpi);
	public static native void lime_gamepad_add_mappings(Object mappings);
	public static native void lime_gamepad_event_manager_register(Object callback, Object eventObject);
	public static native Object lime_gamepad_get_device_guid(int id);
	public static native Object lime_gamepad_get_device_name(int id);
	public static native void lime_gamepad_rumble(int id, double lowFrequencyRumble, double highFrequencyRumble, int duration);
	public static native void lime_gl_active_texture(int texture);
	public static native void lime_gl_attach_shader(int program, int shader);
	public static native void lime_gl_begin_query(int target, int query);
	public static native void lime_gl_begin_transform_feedback(int primitiveNode);
	public static native void lime_gl_bind_attrib_location(int program, int index, String name);
	public static native void lime_gl_bind_buffer(int target, int buffer);
	public static native void lime_gl_bind_buffer_base(int target, int index, int buffer);
	public static native void lime_gl_bind_buffer_range(int target, int index, int buffer, Object offset, int size);
	public static native void lime_gl_bind_framebuffer(int target, int framebuffer);
	public static native void lime_gl_bind_renderbuffer(int target, int renderbuffer);
	public static native void lime_gl_bind_sampler(int target, int sampler);
	public static native void lime_gl_bind_texture(int target, int texture);
	public static native void lime_gl_bind_transform_feedback(int target, int transformFeedback);
	public static native void lime_gl_bind_vertex_array(int vertexArray);
	public static native void lime_gl_blend_color(double red, double green, double blue, double alpha);
	public static native void lime_gl_blend_equation(int mode);
	public static native void lime_gl_blend_equation_separate(int modeRGB, int modeAlpha);
	public static native void lime_gl_blend_func(int sfactor, int dfactor);
	public static native void lime_gl_blend_func_separate(int srcRGB, int dstRGB, int srcAlpha, int dstAlpha);
	public static native void lime_gl_blit_framebuffer(int srcX0, int srcY0, int srcX1, int srcY1, int dstX0, int dstY0, int dstX1, int dstY1, int mask, int filter);
	public static native void lime_gl_buffer_data(int target, int size, Object srcData, int usage);
	public static native void lime_gl_buffer_sub_data(int target, int offset, int size, Object srcData);
	public static native int lime_gl_check_framebuffer_status(int target);
	public static native void lime_gl_clear(int mask);
	public static native void lime_gl_clear_bufferfi(int buffer, int drawBuffer, double depth, int stencil);
	public static native void lime_gl_clear_bufferfv(int buffer, int drawBuffer, Object data);
	public static native void lime_gl_clear_bufferiv(int buffer, int drawBuffer, Object data);
	public static native void lime_gl_clear_bufferuiv(int buffer, int drawBuffer, Object data);
	public static native void lime_gl_clear_color(double red, double green, double blue, double alpha);
	public static native void lime_gl_clear_depthf(double depth);
	public static native void lime_gl_clear_stencil(int s);
	public static native int lime_gl_client_wait_sync(Object sync, int flags, int timeoutA, int timeoutB);
	public static native void lime_gl_color_mask(boolean red, boolean green, boolean blue, boolean alpha);
	public static native void lime_gl_compile_shader(int shader);
	public static native void lime_gl_compressed_tex_image_2d(int target, int level, int internalformat, int width, int height, int border, int imageSize, Object data);
	public static native void lime_gl_compressed_tex_image_3d(int target, int level, int internalformat, int width, int height, int depth, int border, int imageSize, Object data);
	public static native void lime_gl_compressed_tex_sub_image_2d(int target, int level, int xoffset, int yoffset, int width, int height, int format, int imageSize, Object data);
	public static native void lime_gl_compressed_tex_sub_image_3d(int target, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int imageSize, Object data);
	public static native void lime_gl_copy_buffer_sub_data(int readTarget, int writeTarget, Object readOffset, Object writeOffset, int size);
	public static native void lime_gl_copy_tex_image_2d(int target, int level, int internalformat, int x, int y, int width, int height, int border);
	public static native void lime_gl_copy_tex_sub_image_2d(int target, int level, int xoffset, int yoffset, int x, int y, int width, int height);
	public static native void lime_gl_copy_tex_sub_image_3d(int target, int level, int xoffset, int yoffset, int zoffset, int x, int y, int width, int height);
	public static native int lime_gl_create_buffer();
	public static native int lime_gl_create_framebuffer();
	public static native int lime_gl_create_program();
	public static native int lime_gl_create_query();
	public static native int lime_gl_create_renderbuffer();
	public static native int lime_gl_create_sampler();
	public static native int lime_gl_create_shader(int type);
	public static native int lime_gl_create_texture();
	public static native int lime_gl_create_transform_feedback();
	public static native int lime_gl_create_vertex_array();
	public static native void lime_gl_cull_face(int mode);
	public static native void lime_gl_delete_buffer(int buffer);
	public static native void lime_gl_delete_framebuffer(int framebuffer);
	public static native void lime_gl_delete_program(int program);
	public static native void lime_gl_delete_query(int query);
	public static native void lime_gl_delete_renderbuffer(int renderbuffer);
	public static native void lime_gl_delete_sampler(int sampler);
	public static native void lime_gl_delete_shader(int shader);
	public static native void lime_gl_delete_sync(Object sync);
	public static native void lime_gl_delete_texture(int texture);
	public static native void lime_gl_delete_transform_feedback(int transformFeedback);
	public static native void lime_gl_delete_vertex_array(int vertexArray);
	public static native void lime_gl_depth_func(int func);
	public static native void lime_gl_depth_mask(boolean flag);
	public static native void lime_gl_depth_rangef(double zNear, double zFar);
	public static native void lime_gl_detach_shader(int program, int shader);
	public static native void lime_gl_disable(int cap);
	public static native void lime_gl_disable_vertex_attrib_array(int index);
	public static native void lime_gl_draw_arrays(int mode, int first, int count);
	public static native void lime_gl_draw_arrays_instanced(int mode, int first, int count, int instanceCount);
	public static native void lime_gl_draw_buffers(Object buffers);
	public static native void lime_gl_draw_elements(int mode, int count, int type, Object offset);
	public static native void lime_gl_draw_elements_instanced(int mode, int count, int type, Object offset, int instanceCount);
	public static native void lime_gl_draw_range_elements(int mode, int start, int end, int count, int type, Object offset);
	public static native void lime_gl_enable(int cap);
	public static native void lime_gl_enable_vertex_attrib_array(int index);
	public static native void lime_gl_end_query(int target);
	public static native void lime_gl_end_transform_feedback();
	public static native Object lime_gl_fence_sync(int condition, int flags);
	public static native void lime_gl_finish();
	public static native void lime_gl_flush();
	public static native void lime_gl_framebuffer_renderbuffer(int target, int attachment, int renderbuffertarget, int renderbuffer);
	public static native void lime_gl_framebuffer_texture2D(int target, int attachment, int textarget, int texture, int level);
	public static native void lime_gl_framebuffer_texture_layer(int target, int attachment, int texture, int level, int layer);
	public static native void lime_gl_front_face(int mode);
	public static native void lime_gl_generate_mipmap(int target);
	public static native Object lime_gl_get_active_attrib(int program, int index);
	public static native Object lime_gl_get_active_uniform(int program, int index);
	public static native Object lime_gl_get_active_uniform_block_name(int program, int uniformBlockIndex);
	public static native int lime_gl_get_active_uniform_blocki(int program, int uniformBlockIndex, int pname);
	public static native void lime_gl_get_active_uniform_blockiv(int program, int uniformBlockIndex, int pname, Object params);
	public static native void lime_gl_get_active_uniformsiv(int program, Object uniformIndices, int pname, Object params);
	public static native Object lime_gl_get_attached_shaders(int program);
	public static native int lime_gl_get_attrib_location(int program, String name);
	public static native boolean lime_gl_get_boolean(int pname);
	public static native void lime_gl_get_booleanv(int pname, Object params);
	public static native int lime_gl_get_buffer_parameteri(int target, int pname);
	public static native void lime_gl_get_buffer_parameteri64v(int target, int index, Object params);
	public static native void lime_gl_get_buffer_parameteriv(int target, int pname, Object params);
	public static native Object lime_gl_get_buffer_pointerv(int target, int pname);
	public static native void lime_gl_get_buffer_sub_data(int target, Object offset, int size, Object data);
	public static native Object lime_gl_get_context_attributes();
	public static native int lime_gl_get_error();
	public static native Object lime_gl_get_extension(String name);
	public static native double lime_gl_get_float(int pname);
	public static native void lime_gl_get_floatv(int pname, Object params);
	public static native int lime_gl_get_frag_data_location(int program, String name);
	public static native int lime_gl_get_framebuffer_attachment_parameteri(int target, int attachment, int pname);
	public static native void lime_gl_get_framebuffer_attachment_parameteriv(int target, int attachment, int pname, Object params);
	public static native int lime_gl_get_integer(int pname);
	public static native void lime_gl_get_integer64i_v(int pname, int index, Object params);
	public static native void lime_gl_get_integer64v(int pname, Object params);
	public static native void lime_gl_get_integeri_v(int pname, int index, Object params);
	public static native void lime_gl_get_integerv(int pname, Object params);
	public static native void lime_gl_get_internalformativ(int target, int internalformat, int pname, int bufSize, Object params);
	public static native void lime_gl_get_program_binary(int program, int binaryFormat, Object bytes);
	public static native Object lime_gl_get_program_info_log(int program);
	public static native int lime_gl_get_programi(int program, int pname);
	public static native void lime_gl_get_programiv(int program, int pname, Object params);
	public static native int lime_gl_get_query_objectui(int target, int pname);
	public static native void lime_gl_get_query_objectuiv(int target, int pname, Object params);
	public static native int lime_gl_get_queryi(int target, int pname);
	public static native void lime_gl_get_queryiv(int target, int pname, Object params);
	public static native int lime_gl_get_renderbuffer_parameteri(int target, int pname);
	public static native void lime_gl_get_renderbuffer_parameteriv(int target, int pname, Object params);
	public static native double lime_gl_get_sampler_parameterf(int target, int pname);
	public static native void lime_gl_get_sampler_parameterfv(int target, int pname, Object params);
	public static native int lime_gl_get_sampler_parameteri(int target, int pname);
	public static native void lime_gl_get_sampler_parameteriv(int target, int pname, Object params);
	public static native Object lime_gl_get_shader_info_log(int shader);
	public static native Object lime_gl_get_shader_precision_format(int shadertype, int precisiontype);
	public static native Object lime_gl_get_shader_source(int shader);
	public static native int lime_gl_get_shaderi(int shader, int pname);
	public static native void lime_gl_get_shaderiv(int shader, int pname, Object params);
	public static native Object lime_gl_get_string(int pname);
	public static native Object lime_gl_get_stringi(int pname, int index);
	public static native int lime_gl_get_sync_parameteri(Object sync, int pname);
	public static native void lime_gl_get_sync_parameteriv(Object sync, int pname, Object params);
	public static native double lime_gl_get_tex_parameterf(int target, int pname);
	public static native void lime_gl_get_tex_parameterfv(int target, int pname, Object params);
	public static native int lime_gl_get_tex_parameteri(int target, int pname);
	public static native void lime_gl_get_tex_parameteriv(int target, int pname, Object params);
	public static native Object lime_gl_get_transform_feedback_varying(int program, int index);
	public static native int lime_gl_get_uniform_block_index(int program, String uniformBlockName);
	public static native int lime_gl_get_uniform_location(int program, String name);
	public static native double lime_gl_get_uniformf(int program, int location);
	public static native void lime_gl_get_uniformfv(int program, int location, Object params);
	public static native int lime_gl_get_uniformi(int program, int location);
	public static native void lime_gl_get_uniformiv(int program, int location, Object params);
	public static native int lime_gl_get_uniformui(int program, int location);
	public static native void lime_gl_get_uniformuiv(int program, int location, Object params);
	public static native Object lime_gl_get_vertex_attrib_pointerv(int index, int pname);
	public static native double lime_gl_get_vertex_attribf(int index, int pname);
	public static native void lime_gl_get_vertex_attribfv(int index, int pname, Object params);
	public static native int lime_gl_get_vertex_attribi(int index, int pname);
	public static native int lime_gl_get_vertex_attribii(int index, int pname);
	public static native void lime_gl_get_vertex_attribiiv(int index, int pname, Object params);
	public static native int lime_gl_get_vertex_attribiui(int index, int pname);
	public static native void lime_gl_get_vertex_attribiuiv(int index, int pname, Object params);
	public static native void lime_gl_get_vertex_attribiv(int index, int pname, Object params);
	public static native void lime_gl_hint(int target, int mode);
	public static native void lime_gl_invalidate_framebuffer(int target, Object attachments);
	public static native void lime_gl_invalidate_sub_framebuffer(int target, Object attachments, int x, int y, int width, int height);
	public static native boolean lime_gl_is_buffer(int buffer);
	public static native boolean lime_gl_is_enabled(int cap);
	public static native boolean lime_gl_is_framebuffer(int framebuffer);
	public static native boolean lime_gl_is_program(int program);
	public static native boolean lime_gl_is_query(int query);
	public static native boolean lime_gl_is_renderbuffer(int renderbuffer);
	public static native boolean lime_gl_is_sampler(int sampler);
	public static native boolean lime_gl_is_shader(int shader);
	public static native boolean lime_gl_is_sync(Object sync);
	public static native boolean lime_gl_is_texture(int texture);
	public static native boolean lime_gl_is_transform_feedback(int transformFeedback);
	public static native boolean lime_gl_is_vertex_array(int vertexArray);
	public static native void lime_gl_line_width(double width);
	public static native void lime_gl_link_program(int program);
	public static native Object lime_gl_map_buffer_range(int target, Object offset, int length, int access);
	public static native void lime_gl_object_deregister(Object object);
	public static native Object lime_gl_object_from_id(int id, int type);
	public static native Object lime_gl_object_register(int id, int type, Object object);
	public static native void lime_gl_pause_transform_feedback();
	public static native void lime_gl_pixel_storei(int pname, int param);
	public static native void lime_gl_polygon_offset(double factor, double units);
	public static native void lime_gl_program_binary(int program, int binaryFormat, Object binary, int length);
	public static native void lime_gl_program_parameteri(int program, int pname, int value);
	public static native void lime_gl_read_buffer(int src);
	public static native void lime_gl_read_pixels(int x, int y, int width, int height, int format, int type, Object pixels);
	public static native void lime_gl_release_shader_compiler();
	public static native void lime_gl_renderbuffer_storage(int target, int internalformat, int width, int height);
	public static native void lime_gl_renderbuffer_storage_multisample(int target, int samples, int internalformat, int width, int height);
	public static native void lime_gl_resume_transform_feedback();
	public static native void lime_gl_sample_coverage(double value, boolean invert);
	public static native void lime_gl_sampler_parameterf(int sampler, int pname, double param);
	public static native void lime_gl_sampler_parameteri(int sampler, int pname, int param);
	public static native void lime_gl_scissor(int x, int y, int width, int height);
	public static native void lime_gl_shader_binary(Object shaders, int binaryformat, Object binary, int length);
	public static native void lime_gl_shader_source(int shader, String source);
	public static native void lime_gl_stencil_func(int func, int ref, int mask);
	public static native void lime_gl_stencil_func_separate(int face, int func, int ref, int mask);
	public static native void lime_gl_stencil_mask(int mask);
	public static native void lime_gl_stencil_mask_separate(int face, int mask);
	public static native void lime_gl_stencil_op(int fail, int zfail, int zpass);
	public static native void lime_gl_stencil_op_separate(int face, int fail, int zfail, int zpass);
	public static native void lime_gl_tex_image_2d(int target, int level, int internalformat, int width, int height, int border, int format, int type, Object data);
	public static native void lime_gl_tex_image_3d(int target, int level, int internalformat, int width, int height, int depth, int border, int format, int type, Object data);
	public static native void lime_gl_tex_parameterf(int target, int pname, double param);
	public static native void lime_gl_tex_parameteri(int target, int pname, int param);
	public static native void lime_gl_tex_storage_2d(int target, int level, int internalformat, int width, int height);
	public static native void lime_gl_tex_storage_3d(int target, int level, int internalformat, int width, int height, int depth);
	public static native void lime_gl_tex_sub_image_2d(int target, int level, int xoffset, int yoffset, int width, int height, int format, int type, Object data);
	public static native void lime_gl_tex_sub_image_3d(int target, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, Object data);
	public static native void lime_gl_transform_feedback_varyings(int program, Object varyings, int bufferMode);
	public static native void lime_gl_uniform1f(int location, double v0);
	public static native void lime_gl_uniform1fv(int location, int count, Object v);
	public static native void lime_gl_uniform1i(int location, int v0);
	public static native void lime_gl_uniform1iv(int location, int count, Object v);
	public static native void lime_gl_uniform1ui(int location, int v0);
	public static native void lime_gl_uniform1uiv(int location, int count, Object v);
	public static native void lime_gl_uniform2f(int location, double v0, double v1);
	public static native void lime_gl_uniform2fv(int location, int count, Object v);
	public static native void lime_gl_uniform2i(int location, int v0, int v1);
	public static native void lime_gl_uniform2iv(int location, int count, Object v);
	public static native void lime_gl_uniform2ui(int location, int v0, int v1);
	public static native void lime_gl_uniform2uiv(int location, int count, Object v);
	public static native void lime_gl_uniform3f(int location, double v0, double v1, double v2);
	public static native void lime_gl_uniform3fv(int location, int count, Object v);
	public static native void lime_gl_uniform3i(int location, int v0, int v1, int v2);
	public static native void lime_gl_uniform3iv(int location, int count, Object v);
	public static native void lime_gl_uniform3ui(int location, int v0, int v1, int v2);
	public static native void lime_gl_uniform3uiv(int location, int count, Object v);
	public static native void lime_gl_uniform4f(int location, double v0, double v1, double v2, double v3);
	public static native void lime_gl_uniform4fv(int location, int count, Object v);
	public static native void lime_gl_uniform4i(int location, int v0, int v1, int v2, int v3);
	public static native void lime_gl_uniform4iv(int location, int count, Object v);
	public static native void lime_gl_uniform4ui(int location, int v0, int v1, int v2, int v3);
	public static native void lime_gl_uniform4uiv(int location, int count, Object v);
	public static native void lime_gl_uniform_block_binding(int program, int uniformBlockIndex, int uniformBlockBinding);
	public static native void lime_gl_uniform_matrix2fv(int location, int count, boolean transpose, Object value);
	public static native void lime_gl_uniform_matrix2x3fv(int location, int count, boolean transpose, Object value);
	public static native void lime_gl_uniform_matrix2x4fv(int location, int count, boolean transpose, Object value);
	public static native void lime_gl_uniform_matrix3fv(int location, int count, boolean transpose, Object value);
	public static native void lime_gl_uniform_matrix3x2fv(int location, int count, boolean transpose, Object value);
	public static native void lime_gl_uniform_matrix3x4fv(int location, int count, boolean transpose, Object value);
	public static native void lime_gl_uniform_matrix4fv(int location, int count, boolean transpose, Object value);
	public static native void lime_gl_uniform_matrix4x2fv(int location, int count, boolean transpose, Object value);
	public static native void lime_gl_uniform_matrix4x3fv(int location, int count, boolean transpose, Object value);
	public static native boolean lime_gl_unmap_buffer(int target);
	public static native void lime_gl_use_program(int program);
	public static native void lime_gl_validate_program(int program);
	public static native void lime_gl_vertex_attrib1f(int indx, double v0);
	public static native void lime_gl_vertex_attrib1fv(int indx, Object values);
	public static native void lime_gl_vertex_attrib2f(int indx, double v0, double v1);
	public static native void lime_gl_vertex_attrib2fv(int indx, Object values);
	public static native void lime_gl_vertex_attrib3f(int indx, double v0, double v1, double v2);
	public static native void lime_gl_vertex_attrib3fv(int indx, Object values);
	public static native void lime_gl_vertex_attrib4f(int indx, double v0, double v1, double v2, double v3);
	public static native void lime_gl_vertex_attrib4fv(int indx, Object values);
	public static native void lime_gl_vertex_attrib_divisor(int indx, int divisor);
	public static native void lime_gl_vertex_attrib_ipointer(int indx, int size, int type, int stride, Object offset);
	public static native void lime_gl_vertex_attrib_pointer(int indx, int size, int type, boolean normalized, int stride, Object offset);
	public static native void lime_gl_vertex_attribi4i(int indx, int v0, int v1, int v2, int v3);
	public static native void lime_gl_vertex_attribi4iv(int indx, Object values);
	public static native void lime_gl_vertex_attribi4ui(int indx, int v0, int v1, int v2, int v3);
	public static native void lime_gl_vertex_attribi4uiv(int indx, Object values);
	public static native void lime_gl_viewport(int x, int y, int width, int height);
	public static native void lime_gl_wait_sync(Object sync, int flags, int timeoutA, int timeoutB);
	public static native Object lime_gzip_compress(Object data, Object bytes);
	public static native Object lime_gzip_decompress(Object data, Object bytes);
	public static native void lime_haptic_vibrate(int period, int duration);
	public static native Object lime_hb_blob_create(Object data, int length, int memoryMode);
	public static native Object lime_hb_blob_create_sub_blob(Object parent, int offset, int length);
	public static native double lime_hb_blob_get_data(Object blob);
	public static native double lime_hb_blob_get_data_writable(Object blob);
	public static native Object lime_hb_blob_get_empty();
	public static native int lime_hb_blob_get_length(Object blob);
	public static native boolean lime_hb_blob_is_immutable(Object blob);
	public static native void lime_hb_blob_make_immutable(Object blob);
	public static native void lime_hb_buffer_add(Object buffer, int codepoint, int cluster);
	public static native void lime_hb_buffer_add_codepoints(Object buffer, Object text, int textLength, int itemOffset, int itemLength);
	public static native void lime_hb_buffer_add_hxstring(Object buffer, String text, int itemOffset, int itemLength);
	public static native void lime_hb_buffer_add_utf16(Object buffer, Object text, int textLength, int itemOffset, int itemLength);
	public static native void lime_hb_buffer_add_utf32(Object buffer, Object text, int textLength, int itemOffset, int itemLength);
	public static native void lime_hb_buffer_add_utf8(Object buffer, String text, int itemOffset, int itemLength);
	public static native boolean lime_hb_buffer_allocation_successful(Object buffer);
	public static native void lime_hb_buffer_clear_contents(Object buffer);
	public static native Object lime_hb_buffer_create();
	public static native int lime_hb_buffer_get_cluster_level(Object buffer);
	public static native int lime_hb_buffer_get_content_type(Object buffer);
	public static native int lime_hb_buffer_get_direction(Object buffer);
	public static native Object lime_hb_buffer_get_empty();
	public static native int lime_hb_buffer_get_flags(Object buffer);
	public static native Object lime_hb_buffer_get_glyph_infos(Object buffer, Object bytes);
	public static native Object lime_hb_buffer_get_glyph_positions(Object buffer, Object bytes);
	public static native Object lime_hb_buffer_get_language(Object buffer);
	public static native int lime_hb_buffer_get_length(Object buffer);
	public static native int lime_hb_buffer_get_replacement_codepoint(Object buffer);
	public static native int lime_hb_buffer_get_script(Object buffer);
	public static native void lime_hb_buffer_get_segment_properties(Object buffer, Object props);
	public static native void lime_hb_buffer_guess_segment_properties(Object buffer);
	public static native void lime_hb_buffer_normalize_glyphs(Object buffer);
	public static native boolean lime_hb_buffer_preallocate(Object buffer, int size);
	public static native void lime_hb_buffer_reset(Object buffer);
	public static native void lime_hb_buffer_reverse(Object buffer);
	public static native void lime_hb_buffer_reverse_clusters(Object buffer);
	public static native int lime_hb_buffer_serialize_format_from_string(String str);
	public static native Object lime_hb_buffer_serialize_format_to_string(int format);
	public static native Object lime_hb_buffer_serialize_list_formats();
	public static native void lime_hb_buffer_set_cluster_level(Object buffer, int clusterLevel);
	public static native void lime_hb_buffer_set_content_type(Object buffer, int contentType);
	public static native void lime_hb_buffer_set_direction(Object buffer, int direction);
	public static native void lime_hb_buffer_set_flags(Object buffer, int flags);
	public static native void lime_hb_buffer_set_language(Object buffer, Object language);
	public static native boolean lime_hb_buffer_set_length(Object buffer, int length);
	public static native void lime_hb_buffer_set_replacement_codepoint(Object buffer, int replacement);
	public static native void lime_hb_buffer_set_script(Object buffer, int script);
	public static native void lime_hb_buffer_set_segment_properties(Object buffer, Object props);
	public static native Object lime_hb_face_create(Object blob, int index);
	public static native Object lime_hb_face_get_empty();
	public static native int lime_hb_face_get_glyph_count(Object face);
	public static native int lime_hb_face_get_index(Object face);
	public static native int lime_hb_face_get_upem(Object face);
	public static native boolean lime_hb_face_is_immutable(Object face);
	public static native void lime_hb_face_make_immutable(Object face);
	public static native Object lime_hb_face_reference_blob(Object face);
	public static native Object lime_hb_face_reference_table(Object face, int tag);
	public static native void lime_hb_face_set_glyph_count(Object face, int glyphCount);
	public static native void lime_hb_face_set_index(Object face, int index);
	public static native void lime_hb_face_set_upem(Object face, int upem);
	public static native Object lime_hb_feature_from_string(String str);
	public static native Object lime_hb_feature_to_string(Object feature);
	public static native void lime_hb_font_add_glyph_origin_for_direction(Object font, int glyph, int direction, int x, int y);
	public static native Object lime_hb_font_create(Object face);
	public static native Object lime_hb_font_create_sub_font(Object parent);
	public static native Object lime_hb_font_get_empty();
	public static native Object lime_hb_font_get_face(Object font);
	public static native Object lime_hb_font_get_glyph_advance_for_direction(Object font, int glyph, int direction);
	public static native Object lime_hb_font_get_glyph_kerning_for_direction(Object font, int firstGlyph, int secondGlyph, int direction);
	public static native Object lime_hb_font_get_glyph_origin_for_direction(Object font, int glyph, int direction);
	public static native Object lime_hb_font_get_parent(Object font);
	public static native Object lime_hb_font_get_ppem(Object font);
	public static native Object lime_hb_font_get_scale(Object font);
	public static native int lime_hb_font_glyph_from_string(Object font, String s);
	public static native Object lime_hb_font_glyph_to_string(Object font, int codepoint);
	public static native boolean lime_hb_font_is_immutable(Object font);
	public static native void lime_hb_font_make_immutable(Object font);
	public static native void lime_hb_font_set_ppem(Object font, int xppem, int yppem);
	public static native void lime_hb_font_set_scale(Object font, int xScale, int yScale);
	public static native void lime_hb_font_subtract_glyph_origin_for_direction(Object font, int glyph, int direction, int x, int y);
	public static native void lime_hb_ft_font_changed(Object font);
	public static native Object lime_hb_ft_font_create(Object font);
	public static native Object lime_hb_ft_font_create_referenced(Object font);
	public static native int lime_hb_ft_font_get_load_flags(Object font);
	public static native void lime_hb_ft_font_set_load_flags(Object font, int loadFlags);
	public static native Object lime_hb_language_from_string(String str);
	public static native Object lime_hb_language_get_default();
	public static native Object lime_hb_language_to_string(Object language);
	public static native boolean lime_hb_segment_properties_equal(Object a, Object b);
	public static native int lime_hb_segment_properties_hash(Object p);
	public static native void lime_hb_set_add(Object set, int codepoint);
	public static native void lime_hb_set_add_range(Object set, int first, int last);
	public static native boolean lime_hb_set_allocation_successful(Object set);
	public static native void lime_hb_set_clear(Object set);
	public static native Object lime_hb_set_create();
	public static native void lime_hb_set_del(Object set, int codepoint);
	public static native void lime_hb_set_del_range(Object set, int first, int last);
	public static native Object lime_hb_set_get_empty();
	public static native int lime_hb_set_get_max(Object set);
	public static native int lime_hb_set_get_min(Object set);
	public static native int lime_hb_set_get_population(Object set);
	public static native boolean lime_hb_set_has(Object set, int codepoint);
	public static native void lime_hb_set_intersect(Object set, Object other);
	public static native void lime_hb_set_invert(Object set);
	public static native boolean lime_hb_set_is_empty(Object set);
	public static native boolean lime_hb_set_is_equal(Object set, Object other);
	public static native int lime_hb_set_next(Object set);
	public static native Object lime_hb_set_next_range(Object set);
	public static native void lime_hb_set_set(Object set, Object other);
	public static native void lime_hb_set_subtract(Object set, Object other);
	public static native void lime_hb_set_symmetric_difference(Object set, Object other);
	public static native void lime_hb_set_union(Object set, Object other);
	public static native void lime_hb_shape(Object font, Object buffer, Object features);
	public static native void lime_image_data_util_color_transform(Object image, Object rect, Object colorMatrix);
	public static native void lime_image_data_util_copy_channel(Object image, Object sourceImage, Object sourceRect, Object destPoint, int srcChannel, int destChannel);
	public static native void lime_image_data_util_copy_pixels(Object image, Object sourceImage, Object sourceRect, Object destPoint, Object alphaImage, Object alphaPoint, boolean mergeAlpha);
	public static native void lime_image_data_util_fill_rect(Object image, Object rect, int rg, int ba);
	public static native void lime_image_data_util_flood_fill(Object image, int x, int y, int rg, int ba);
	public static native void lime_image_data_util_get_pixels(Object image, Object rect, int format, Object bytes);
	public static native void lime_image_data_util_merge(Object image, Object sourceImage, Object sourceRect, Object destPoint, int redMultiplier, int greenMultiplier, int blueMultiplier, int alphaMultiplier);
	public static native void lime_image_data_util_multiply_alpha(Object image);
	public static native void lime_image_data_util_resize(Object image, Object buffer, int width, int height);
	public static native void lime_image_data_util_set_format(Object image, int format);
	public static native void lime_image_data_util_set_pixels(Object image, Object rect, Object bytes, int offset, int format, int endian);
	public static native int lime_image_data_util_threshold(Object image, Object sourceImage, Object sourceRect, Object destPoint, int operation, int thresholdRG, int thresholdBA, int colorRG, int colorBA, int maskRG, int maskBA, boolean copySource);
	public static native void lime_image_data_util_unmultiply_alpha(Object image);
	public static native Object lime_image_encode(Object data, int type, int quality, Object bytes);
	public static native Object lime_image_load(Object data, Object buffer);
	public static native Object lime_image_load_bytes(Object data, Object buffer);
	public static native Object lime_image_load_file(Object path, Object buffer);
	public static native byte[] lime_jvm_audio_decode(byte[] data, int[] outInfo); // OGG/WAV -> 16-bit PCM (libvorbis); outInfo = {sampleRate, channels, bitsPerSample}
	public static native Object lime_jni_call_member(Object jniMethod, Object jniObject, Object args);
	public static native Object lime_jni_call_static(Object jniMethod, Object args);
	public static native Object lime_jni_create_field(String className, String field, String signature, boolean isStatic);
	public static native Object lime_jni_create_method(String className, String method, String signature, boolean isStatic, boolean quiet);
	public static native double lime_jni_get_env();
	public static native Object lime_jni_get_member(Object jniField, Object jniObject);
	public static native Object lime_jni_get_static(Object jniField);
	public static native void lime_jni_post_ui_callback(Object callback);
	public static native void lime_jni_set_member(Object jniField, Object jniObject, Object value);
	public static native void lime_jni_set_static(Object jniField, Object value);
	public static native void lime_joystick_event_manager_register(Object callback, Object eventObject);
	public static native Object lime_joystick_get_device_guid(int id);
	public static native Object lime_joystick_get_device_name(int id);
	public static native int lime_joystick_get_num_axes(int id);
	public static native int lime_joystick_get_num_buttons(int id);
	public static native int lime_joystick_get_num_hats(int id);
	public static native Object lime_jpeg_decode_bytes(Object data, boolean decodeData, Object buffer);
	public static native Object lime_jpeg_decode_file(String path, boolean decodeData, Object buffer);
	public static native int lime_key_code_from_scan_code(int scanCode);
	public static native int lime_key_code_to_scan_code(int keyCode);
	public static native void lime_key_event_manager_register(Object callback, Object eventObject);
	public static native Object lime_lzma_compress(Object data, Object bytes);
	public static native Object lime_lzma_decompress(Object data, Object bytes);
	public static native void lime_mouse_event_manager_register(Object callback, Object eventObject);
	public static native void lime_neko_execute(String module);
	public static native void lime_orientation_event_manager_register(Object callback, Object eventObject);
	public static native Object lime_png_decode_bytes(Object data, boolean decodeData, Object buffer);
	public static native Object lime_png_decode_file(String path, boolean decodeData, Object buffer);
	public static native void lime_render_event_manager_register(Object callback, Object eventObject);
	public static native Object lime_sdl_sound_get_info_from_bytes(Object bytes);
	public static native Object lime_sdl_sound_get_info_from_file(String path);
	public static native void lime_sdl_sound_stream_clear(Object stream);
	public static native Object lime_sdl_sound_stream_from_bytes(Object bytes);
	public static native Object lime_sdl_sound_stream_from_file(String path);
	public static native int lime_sdl_sound_stream_read(Object stream, Object buffer, int length);
	public static native boolean lime_sdl_sound_stream_rewind(Object stream);
	public static native boolean lime_sdl_sound_stream_seek(Object stream, int ms);
	public static native void lime_sensor_event_manager_register(Object callback, Object eventObject);
	public static native boolean lime_system_get_allow_screen_timeout();
	public static native Object lime_system_get_device_model();
	public static native int lime_system_get_device_orientation();
	public static native Object lime_system_get_device_vendor();
	public static native Object lime_system_get_directory(int type, String company, String title);
	public static native Object lime_system_get_display(int index);
	public static native int lime_jvm_screen_width();  // logical desktop size (SDL desktop display mode); callers scale by window.scale
	public static native int lime_jvm_screen_height();
	public static native boolean lime_system_get_ios_tablet();
	public static native int lime_system_get_num_displays();
	public static native Object lime_system_get_platform_label();
	public static native Object lime_system_get_platform_name();
	public static native Object lime_system_get_platform_version();
	public static native double lime_system_get_timer();
	public static native void lime_system_open_file(String path);
	public static native void lime_system_open_url(String url, String target);
	public static native boolean lime_system_set_allow_screen_timeout(boolean value);
	public static native void lime_text_event_manager_register(Object callback, Object eventObject);
	public static native void lime_touch_event_manager_register(Object callback, Object eventObject);
	public static native int lime_vorbis_file_bitrate(Object vorbisFile, int bitstream);
	public static native int lime_vorbis_file_bitrate_instant(Object vorbisFile);
	public static native void lime_vorbis_file_clear(Object vorbisFile);
	public static native Object lime_vorbis_file_comment(Object vorbisFile, int bitstream);
	public static native Object lime_vorbis_file_crosslap(Object vorbisFile, Object otherVorbisFile);
	public static native Object lime_vorbis_file_from_bytes(Object bytes);
	public static native Object lime_vorbis_file_from_file(String path);
	public static native Object lime_vorbis_file_info(Object vorbisFile, int bitstream);
	public static native int lime_vorbis_file_pcm_seek(Object vorbisFile, Object posLow, Object posHigh);
	public static native int lime_vorbis_file_pcm_seek_lap(Object vorbisFile, Object posLow, Object posHigh);
	public static native int lime_vorbis_file_pcm_seek_page(Object vorbisFile, Object posLow, Object posHigh);
	public static native int lime_vorbis_file_pcm_seek_page_lap(Object vorbisFile, Object posLow, Object posHigh);
	public static native Object lime_vorbis_file_pcm_tell(Object vorbisFile);
	public static native Object lime_vorbis_file_pcm_total(Object vorbisFile, int bitstream);
	public static native int lime_vorbis_file_raw_seek(Object vorbisFile, Object posLow, Object posHigh);
	public static native int lime_vorbis_file_raw_seek_lap(Object vorbisFile, Object posLow, Object posHigh);
	public static native Object lime_vorbis_file_raw_tell(Object vorbisFile);
	public static native Object lime_vorbis_file_raw_total(Object vorbisFile, int bitstream);
	public static native Object lime_vorbis_file_read(Object vorbisFile, Object buffer, int position, int length, boolean bigendianp, int word, boolean signed);
	public static native Object lime_vorbis_file_read_float(Object vorbisFile, Object pcmChannels, int samples);
	public static native boolean lime_vorbis_file_seekable(Object vorbisFile);
	public static native int lime_vorbis_file_serial_number(Object vorbisFile, int bitstream);
	public static native int lime_vorbis_file_streams(Object vorbisFile);
	public static native int lime_vorbis_file_time_seek(Object vorbisFile, double s);
	public static native int lime_vorbis_file_time_seek_lap(Object vorbisFile, double s);
	public static native int lime_vorbis_file_time_seek_page(Object vorbisFile, double s);
	public static native int lime_vorbis_file_time_seek_page_lap(Object vorbisFile, double s);
	public static native double lime_vorbis_file_time_tell(Object vorbisFile);
	public static native double lime_vorbis_file_time_total(Object vorbisFile, int bitstream);
	public static native void lime_window_alert(Object handle, String message, String title);
	public static native void lime_window_close(Object handle);
	public static native void lime_window_context_flip(Object handle);
	public static native Object lime_window_context_lock(Object handle);
	public static native void lime_window_context_make_current(Object handle);
	public static native void lime_window_context_unlock(Object handle);
	public static native Object lime_window_create(Object application, int width, int height, int flags, String title);
	public static native void lime_window_event_manager_register(Object callback, Object eventObject);
	public static native void lime_window_focus(Object handle);
	public static native double lime_window_get_context(Object handle);
	public static native Object lime_window_get_context_type(Object handle);
	public static native int lime_window_get_display(Object handle);
	public static native Object lime_window_get_display_mode(Object handle);
	public static native int lime_window_get_height(Object handle);
	public static native int lime_window_get_id(Object handle);
	public static native boolean lime_window_get_mouse_lock(Object handle);
	public static native double lime_window_get_opacity(Object handle);
	public static native double lime_window_get_scale(Object handle);
	public static native boolean lime_window_get_text_input_enabled(Object handle);
	public static native int lime_window_get_width(Object handle);
	public static native int lime_window_get_x(Object handle);
	public static native int lime_window_get_y(Object handle);
	public static native void lime_window_move(Object handle, int x, int y);
	public static native Object lime_window_read_pixels(Object handle, Object rect, Object imageBuffer);
	public static native void lime_window_resize(Object handle, int width, int height);
	public static native boolean lime_window_set_always_on_top(Object handle, boolean alwaysOnTop);
	public static native boolean lime_window_set_borderless(Object handle, boolean borderless);
	public static native void lime_window_set_cursor(Object handle, int cursor);
	public static native Object lime_window_set_display_mode(Object handle, Object displayMode);
	public static native boolean lime_window_set_fullscreen(Object handle, boolean fullscreen);
	public static native void lime_window_set_icon(Object handle, Object buffer);
	public static native boolean lime_window_set_maximized(Object handle, boolean maximized);
	public static native void lime_window_set_maximum_size(Object handle, int width, int height);
	public static native boolean lime_window_set_minimized(Object handle, boolean minimized);
	public static native void lime_window_set_minimum_size(Object handle, int width, int height);
	public static native void lime_window_set_mouse_lock(Object handle, boolean mouseLock);
	public static native void lime_window_set_opacity(Object handle, double value);
	public static native boolean lime_window_set_resizable(Object handle, boolean resizable);
	public static native void lime_window_set_text_input_enabled(Object handle, boolean enabled);
	public static native void lime_window_set_text_input_rect(Object handle, Object rect);
	public static native Object lime_window_set_title(Object handle, String title);
	public static native boolean lime_window_set_visible(Object handle, boolean visible);
	public static native void lime_window_warp_mouse(Object handle, int x, int y);
	public static native Object lime_zlib_compress(Object data, Object bytes);
	public static native Object lime_zlib_decompress(Object data, Object bytes);
}