package lime.jni;

@:native("lime.jni.Lime")
extern class Lime
{
	static function lime_gl_buffer_data_jvm(target:Int, size:Int, data:haxe.io.BytesData, offset:Int, usage:Int):Void;
	static function lime_gl_buffer_sub_data_jvm(target:Int, dstByteOffset:Int, size:Int, data:haxe.io.BytesData, offset:Int):Void;
	static function lime_gl_tex_image_2d_jvm(target:Int, level:Int, internalformat:Int, width:Int, height:Int, border:Int, format:Int, type:Int, data:haxe.io.BytesData, offset:Int):Void;
	static function lime_gl_uniform_jvm(kind:Int, location:Int, count:Int, transpose:Bool, data:haxe.io.BytesData, offset:Int):Void;

	static function lime_cairo_image_surface_create_for_data_jvm(data:haxe.io.BytesData, offset:Int, format:Int, width:Int, height:Int, stride:Int):Dynamic;

	static function lime_hb_buffer_get_glyph_infos_jvm(buffer:Dynamic):haxe.io.BytesData;
	static function lime_hb_buffer_get_glyph_positions_jvm(buffer:Dynamic):haxe.io.BytesData;

	static function lime_font_load_bytes_jvm(data:haxe.io.BytesData, length:Int):Dynamic;
	static function lime_cairo_show_glyphs_jvm(handle:Dynamic, glyphs:haxe.io.BytesData, count:Int):Void;
	static function lime_teavm_sync_fetch(url:String):haxe.io.BytesData;
	static function lime_cairo_get_current_point_d(handle:Dynamic, i:Int):Float;
	static function lime_cairo_get_matrix_d(handle:Dynamic, i:Int):Float;
	static function lime_cairo_pattern_get_matrix_d(handle:Dynamic, i:Int):Float;
	static function lime_cairo_transform_flat(handle:Dynamic, a:Float, b:Float, c:Float, d:Float, tx:Float, ty:Float):Void;
	static function lime_cairo_pattern_set_matrix_flat(handle:Dynamic, a:Float, b:Float, c:Float, d:Float, tx:Float, ty:Float):Void;

	static function lime_al_auxf(aux:Dynamic, param:Int, value:Float):Void;
	static function lime_al_auxfv(aux:Dynamic, param:Int, values:Dynamic):Void;
	static function lime_al_auxi(aux:Dynamic, param:Int, value:Dynamic):Void;
	static function lime_al_auxiv(aux:Dynamic, param:Int, values:Dynamic):Void;
	static function lime_al_buffer3f(buffer:Dynamic, param:Int, value1:Float, value2:Float, value3:Float):Void;
	static function lime_al_buffer3i(buffer:Dynamic, param:Int, value1:Int, value2:Int, value3:Int):Void;
	static function lime_al_buffer_data(buffer:Dynamic, format:Int, data:Dynamic, size:Int, freq:Int):Void;
	static function lime_al_bufferf(buffer:Dynamic, param:Int, value:Float):Void;
	static function lime_al_bufferfv(buffer:Dynamic, param:Int, values:Dynamic):Void;
	static function lime_al_bufferi(buffer:Dynamic, param:Int, value:Int):Void;
	static function lime_al_bufferiv(buffer:Dynamic, param:Int, values:Dynamic):Void;
	static function lime_al_cleanup():Void;
	static function lime_al_delete_buffer(buffer:Dynamic):Void;
	static function lime_al_delete_buffers(n:Int, buffers:Dynamic):Void;
	static function lime_al_delete_source(source:Dynamic):Void;
	static function lime_al_delete_sources(n:Int, sources:Dynamic):Void;
	static function lime_al_disable(capability:Int):Void;
	static function lime_al_distance_model(distanceModel:Int):Void;
	static function lime_al_doppler_factor(value:Float):Void;
	static function lime_al_doppler_velocity(value:Float):Void;
	static function lime_al_effectf(effect:Dynamic, param:Int, value:Float):Void;
	static function lime_al_effectfv(effect:Dynamic, param:Int, values:Dynamic):Void;
	static function lime_al_effecti(effect:Dynamic, param:Int, value:Int):Void;
	static function lime_al_effectiv(effect:Dynamic, param:Int, values:Dynamic):Void;
	static function lime_al_enable(capability:Int):Void;
	static function lime_al_filterf(filter:Dynamic, param:Int, value:Float):Void;
	static function lime_al_filteri(filter:Dynamic, param:Int, value:Dynamic):Void;
	static function lime_al_gen_aux():Dynamic;
	static function lime_al_gen_buffer():Dynamic;
	static function lime_al_gen_buffers(n:Int):Dynamic;
	static function lime_al_gen_effect():Dynamic;
	static function lime_al_gen_filter():Dynamic;
	static function lime_al_gen_source():Dynamic;
	static function lime_al_gen_sources(n:Int):Dynamic;
	static function lime_al_get_boolean(param:Int):Bool;
	static function lime_al_get_booleanv(param:Int, count:Int):Dynamic;
	static function lime_al_get_buffer3f(buffer:Dynamic, param:Int):Dynamic;
	static function lime_al_get_buffer3i(buffer:Dynamic, param:Int):Dynamic;
	static function lime_al_get_bufferf(buffer:Dynamic, param:Int):Float;
	static function lime_al_get_bufferfv(buffer:Dynamic, param:Int, count:Int):Dynamic;
	static function lime_al_get_bufferi(buffer:Dynamic, param:Int):Int;
	static function lime_al_get_bufferiv(buffer:Dynamic, param:Int, count:Int):Dynamic;
	static function lime_al_get_double(param:Int):Float;
	static function lime_al_get_doublev(param:Int, count:Int):Dynamic;
	static function lime_al_get_enum_value(ename:String):Int;
	static function lime_al_get_error():Int;
	static function lime_al_get_filteri(filter:Dynamic, param:Int):Int;
	static function lime_al_get_float(param:Int):Float;
	static function lime_al_get_floatv(param:Int, count:Int):Dynamic;
	static function lime_al_get_integer(param:Int):Int;
	static function lime_al_get_integerv(param:Int, count:Int):Dynamic;
	static function lime_al_get_listener3f(param:Int):Dynamic;
	static function lime_al_get_listener3i(param:Int):Dynamic;
	static function lime_al_get_listenerf(param:Int):Float;
	static function lime_al_get_listenerfv(param:Int, count:Int):Dynamic;
	static function lime_al_get_listeneri(param:Int):Int;
	static function lime_al_get_listeneriv(param:Int, count:Int):Dynamic;
	static function lime_al_get_proc_address(fname:String):Float;
	static function lime_al_get_source3f(source:Dynamic, param:Int):Dynamic;
	static function lime_al_get_source3i(source:Dynamic, param:Int):Dynamic;
	static function lime_al_get_sourcef(source:Dynamic, param:Int):Float;
	static function lime_al_get_sourcefv(source:Dynamic, param:Int, count:Int):Dynamic;
	static function lime_al_get_sourcei(source:Dynamic, param:Int):Dynamic;
	static function lime_al_get_sourceiv(source:Dynamic, param:Int, count:Int):Dynamic;
	static function lime_al_get_string(param:Int):Dynamic;
	static function lime_al_is_aux(aux:Dynamic):Bool;
	static function lime_al_is_buffer(buffer:Dynamic):Bool;
	static function lime_al_is_effect(effect:Dynamic):Bool;
	static function lime_al_is_enabled(capability:Int):Bool;
	static function lime_al_is_extension_present(extname:String):Bool;
	static function lime_al_is_filter(filter:Dynamic):Bool;
	static function lime_al_is_source(source:Dynamic):Bool;
	static function lime_al_listener3f(param:Int, value1:Float, value2:Float, value3:Float):Void;
	static function lime_al_listener3i(param:Int, value1:Int, value2:Int, value3:Int):Void;
	static function lime_al_listenerf(param:Int, value1:Float):Void;
	static function lime_al_listenerfv(param:Int, values:Dynamic):Void;
	static function lime_al_listeneri(param:Int, value1:Int):Void;
	static function lime_al_listeneriv(param:Int, values:Dynamic):Void;
	static function lime_al_remove_direct_filter(source:Dynamic):Void;
	static function lime_al_remove_send(source:Dynamic, index:Int):Void;
	static function lime_al_source3f(source:Dynamic, param:Int, value1:Float, value2:Float, value3:Float):Void;
	static function lime_al_source3i(source:Dynamic, param:Int, value1:Dynamic, value2:Int, value3:Int):Void;
	static function lime_al_source_pause(source:Dynamic):Void;
	static function lime_al_source_pausev(n:Int, sources:Dynamic):Void;
	static function lime_al_source_play(source:Dynamic):Void;
	static function lime_al_source_playv(n:Int, sources:Dynamic):Void;
	static function lime_al_source_queue_buffers(source:Dynamic, nb:Int, buffers:Dynamic):Void;
	static function lime_al_source_rewind(source:Dynamic):Void;
	static function lime_al_source_rewindv(n:Int, sources:Dynamic):Void;
	static function lime_al_source_stop(source:Dynamic):Void;
	static function lime_al_source_stopv(n:Int, sources:Dynamic):Void;
	static function lime_al_source_unqueue_buffers(source:Dynamic, nb:Int):Dynamic;
	static function lime_al_sourcef(source:Dynamic, param:Int, value:Float):Void;
	static function lime_al_sourcefv(source:Dynamic, param:Int, values:Dynamic):Void;
	static function lime_al_sourcei(source:Dynamic, param:Int, value:Dynamic):Void;
	static function lime_al_sourceiv(source:Dynamic, param:Int, values:Dynamic):Void;
	static function lime_al_speed_of_sound(speed:Float):Void;
	static function lime_alc_close_device(device:Dynamic):Bool;
	static function lime_alc_create_context(device:Dynamic, attrlist:Dynamic):Dynamic;
	static function lime_alc_destroy_context(context:Dynamic):Void;
	static function lime_alc_get_contexts_device(context:Dynamic):Dynamic;
	static function lime_alc_get_current_context():Dynamic;
	static function lime_alc_get_error(device:Dynamic):Int;
	static function lime_alc_get_integerv(device:Dynamic, param:Int, size:Int):Dynamic;
	static function lime_alc_get_string(device:Dynamic, param:Int):Dynamic;
	static function lime_alc_make_context_current(context:Dynamic):Bool;
	static function lime_alc_open_device(devicename:String):Dynamic;
	static function lime_alc_pause_device(device:Dynamic):Void;
	static function lime_alc_process_context(context:Dynamic):Void;
	static function lime_alc_resume_device(device:Dynamic):Void;
	static function lime_alc_suspend_context(context:Dynamic):Void;
	static function lime_application_create():Dynamic;
	static function lime_application_event_manager_register(callback:Dynamic, eventObject:Dynamic):Void;
	static function lime_application_exec(handle:Dynamic):Int;
	static function lime_application_init(handle:Dynamic):Void;
	static function lime_application_quit(handle:Dynamic):Int;
	static function lime_application_set_frame_rate(handle:Dynamic, value:Float):Void;
	static function lime_application_set_main_loop(handle:Dynamic, profile:Int, frameRate:Float, timePrecision:Int, busyWait:Int, uncapMode:Int):Void;
	static function lime_application_set_vsync_mode(handle:Dynamic, value:Int):Void;
	static function lime_application_update(handle:Dynamic):Bool;
	static function lime_audio_load(data:Dynamic, buffer:Dynamic):Dynamic;
	static function lime_audio_load_bytes(data:Dynamic, buffer:Dynamic):Dynamic;
	static function lime_audio_load_file(path:Dynamic, buffer:Dynamic):Dynamic;
	static function lime_bytes_from_data_pointer(data:Float, length:Int, bytes:Dynamic):Dynamic;
	static function lime_bytes_get_data_pointer(data:Dynamic):Float;
	static function lime_bytes_get_data_pointer_offset(data:Dynamic, offset:Int):Float;
	static function lime_bytes_read_file(path:String, bytes:Dynamic):Dynamic;
	static function lime_cairo_arc(handle:Dynamic, xc:Float, yc:Float, radius:Float, angle1:Float, angle2:Float):Void;
	static function lime_cairo_arc_negative(handle:Dynamic, xc:Float, yc:Float, radius:Float, angle1:Float, angle2:Float):Void;
	static function lime_cairo_clip(handle:Dynamic):Void;
	static function lime_cairo_clip_extents(handle:Dynamic, x1:Float, y1:Float, x2:Float, y2:Float):Void;
	static function lime_cairo_clip_preserve(handle:Dynamic):Void;
	static function lime_cairo_close_path(handle:Dynamic):Void;
	static function lime_cairo_copy_page(handle:Dynamic):Void;
	static function lime_cairo_create(handle:Dynamic):Dynamic;
	static function lime_cairo_curve_to(handle:Dynamic, x1:Float, y1:Float, x2:Float, y2:Float, x3:Float, y3:Float):Void;
	static function lime_cairo_fill(handle:Dynamic):Void;
	static function lime_cairo_fill_extents(handle:Dynamic, x1:Float, y1:Float, x2:Float, y2:Float):Void;
	static function lime_cairo_fill_preserve(handle:Dynamic):Void;
	static function lime_cairo_font_face_status(handle:Dynamic):Int;
	static function lime_cairo_font_options_create():Dynamic;
	static function lime_cairo_font_options_get_antialias(handle:Dynamic):Int;
	static function lime_cairo_font_options_get_hint_metrics(handle:Dynamic):Int;
	static function lime_cairo_font_options_get_hint_style(handle:Dynamic):Int;
	static function lime_cairo_font_options_get_subpixel_order(handle:Dynamic):Int;
	static function lime_cairo_font_options_set_antialias(handle:Dynamic, v:Int):Void;
	static function lime_cairo_font_options_set_hint_metrics(handle:Dynamic, v:Int):Void;
	static function lime_cairo_font_options_set_hint_style(handle:Dynamic, v:Int):Void;
	static function lime_cairo_font_options_set_subpixel_order(handle:Dynamic, v:Int):Void;
	static function lime_cairo_ft_font_face_create(face:Dynamic, flags:Int):Dynamic;
	static function lime_cairo_get_antialias(handle:Dynamic):Int;
	static function lime_cairo_get_current_point(handle:Dynamic):Dynamic;
	static function lime_cairo_get_dash(handle:Dynamic):Dynamic;
	static function lime_cairo_get_dash_count(handle:Dynamic):Int;
	static function lime_cairo_get_fill_rule(handle:Dynamic):Int;
	static function lime_cairo_get_font_face(handle:Dynamic):Dynamic;
	static function lime_cairo_get_font_options(handle:Dynamic):Dynamic;
	static function lime_cairo_get_group_target(handle:Dynamic):Dynamic;
	static function lime_cairo_get_line_cap(handle:Dynamic):Int;
	static function lime_cairo_get_line_join(handle:Dynamic):Int;
	static function lime_cairo_get_line_width(handle:Dynamic):Float;
	static function lime_cairo_get_matrix(handle:Dynamic):Dynamic;
	static function lime_cairo_get_miter_limit(handle:Dynamic):Float;
	static function lime_cairo_get_operator(handle:Dynamic):Int;
	static function lime_cairo_get_source(handle:Dynamic):Dynamic;
	static function lime_cairo_get_target(handle:Dynamic):Dynamic;
	static function lime_cairo_get_tolerance(handle:Dynamic):Float;
	static function lime_cairo_has_current_point(handle:Dynamic):Bool;
	static function lime_cairo_identity_matrix(handle:Dynamic):Void;
	static function lime_cairo_image_surface_create(format:Int, width:Int, height:Int):Dynamic;
	static function lime_cairo_image_surface_create_for_data(data:Dynamic, format:Int, width:Int, height:Int, stride:Int):Dynamic;
	static function lime_cairo_image_surface_get_data(handle:Dynamic):Dynamic;
	static function lime_cairo_image_surface_get_format(handle:Dynamic):Int;
	static function lime_cairo_image_surface_get_height(handle:Dynamic):Int;
	static function lime_cairo_image_surface_get_stride(handle:Dynamic):Int;
	static function lime_cairo_image_surface_get_width(handle:Dynamic):Int;
	static function lime_cairo_in_clip(handle:Dynamic, x:Float, y:Float):Bool;
	static function lime_cairo_in_fill(handle:Dynamic, x:Float, y:Float):Bool;
	static function lime_cairo_in_stroke(handle:Dynamic, x:Float, y:Float):Bool;
	static function lime_cairo_line_to(handle:Dynamic, x:Float, y:Float):Void;
	static function lime_cairo_mask(handle:Dynamic, pattern:Dynamic):Void;
	static function lime_cairo_mask_surface(handle:Dynamic, surface:Dynamic, x:Float, y:Float):Void;
	static function lime_cairo_move_to(handle:Dynamic, x:Float, y:Float):Void;
	static function lime_cairo_new_path(handle:Dynamic):Void;
	static function lime_cairo_paint(handle:Dynamic):Void;
	static function lime_cairo_paint_with_alpha(handle:Dynamic, alpha:Float):Void;
	static function lime_cairo_pattern_add_color_stop_rgb(handle:Dynamic, offset:Float, red:Float, green:Float, blue:Float):Void;
	static function lime_cairo_pattern_add_color_stop_rgba(handle:Dynamic, offset:Float, red:Float, green:Float, blue:Float, alpha:Float):Void;
	static function lime_cairo_pattern_create_for_surface(surface:Dynamic):Dynamic;
	static function lime_cairo_pattern_create_linear(x0:Float, y0:Float, x1:Float, y1:Float):Dynamic;
	static function lime_cairo_pattern_create_radial(cx0:Float, cy0:Float, radius0:Float, cx1:Float, cy1:Float, radius1:Float):Dynamic;
	static function lime_cairo_pattern_create_rgb(r:Float, g:Float, b:Float):Dynamic;
	static function lime_cairo_pattern_create_rgba(r:Float, g:Float, b:Float, a:Float):Dynamic;
	static function lime_cairo_pattern_get_color_stop_count(handle:Dynamic):Int;
	static function lime_cairo_pattern_get_extend(handle:Dynamic):Int;
	static function lime_cairo_pattern_get_filter(handle:Dynamic):Int;
	static function lime_cairo_pattern_get_matrix(handle:Dynamic):Dynamic;
	static function lime_cairo_pattern_set_extend(handle:Dynamic, extend:Int):Void;
	static function lime_cairo_pattern_set_filter(handle:Dynamic, filter:Int):Void;
	static function lime_cairo_pattern_set_matrix(handle:Dynamic, matrix:Dynamic):Void;
	static function lime_cairo_pop_group(handle:Dynamic):Dynamic;
	static function lime_cairo_pop_group_to_source(handle:Dynamic):Void;
	static function lime_cairo_push_group(handle:Dynamic):Void;
	static function lime_cairo_push_group_with_content(handle:Dynamic, content:Int):Void;
	static function lime_cairo_rectangle(handle:Dynamic, x:Float, y:Float, width:Float, height:Float):Void;
	static function lime_cairo_rel_curve_to(handle:Dynamic, dx1:Float, dy1:Float, dx2:Float, dy2:Float, dx3:Float, dy3:Float):Void;
	static function lime_cairo_rel_line_to(handle:Dynamic, dx:Float, dy:Float):Void;
	static function lime_cairo_rel_move_to(handle:Dynamic, dx:Float, dy:Float):Void;
	static function lime_cairo_reset_clip(handle:Dynamic):Void;
	static function lime_cairo_restore(handle:Dynamic):Void;
	static function lime_cairo_rotate(handle:Dynamic, amount:Float):Void;
	static function lime_cairo_save(handle:Dynamic):Void;
	static function lime_cairo_scale(handle:Dynamic, x:Float, y:Float):Void;
	static function lime_cairo_set_antialias(handle:Dynamic, cap:Int):Void;
	static function lime_cairo_set_dash(handle:Dynamic, dash:Dynamic):Void;
	static function lime_cairo_set_fill_rule(handle:Dynamic, cap:Int):Void;
	static function lime_cairo_set_font_face(handle:Dynamic, face:Dynamic):Void;
	static function lime_cairo_set_font_options(handle:Dynamic, options:Dynamic):Void;
	static function lime_cairo_set_font_size(handle:Dynamic, size:Float):Void;
	static function lime_cairo_set_line_cap(handle:Dynamic, cap:Int):Void;
	static function lime_cairo_set_line_join(handle:Dynamic, join:Int):Void;
	static function lime_cairo_set_line_width(handle:Dynamic, width:Float):Void;
	static function lime_cairo_set_matrix(handle:Dynamic, a:Float, b:Float, c:Float, d:Float, tx:Float, ty:Float):Void;
	static function lime_cairo_set_miter_limit(handle:Dynamic, miterLimit:Float):Void;
	static function lime_cairo_set_operator(handle:Dynamic, op:Int):Void;
	static function lime_cairo_set_source(handle:Dynamic, pattern:Dynamic):Void;
	static function lime_cairo_set_source_rgb(handle:Dynamic, r:Float, g:Float, b:Float):Void;
	static function lime_cairo_set_source_rgba(handle:Dynamic, r:Float, g:Float, b:Float, a:Float):Void;
	static function lime_cairo_set_source_surface(handle:Dynamic, surface:Dynamic, x:Float, y:Float):Void;
	static function lime_cairo_set_tolerance(handle:Dynamic, tolerance:Float):Void;
	static function lime_cairo_show_glyphs(handle:Dynamic, glyphs:Dynamic):Void;
	static function lime_cairo_show_page(handle:Dynamic):Void;
	static function lime_cairo_show_text(handle:Dynamic, text:String):Void;
	static function lime_cairo_status(handle:Dynamic):Int;
	static function lime_cairo_stroke(handle:Dynamic):Void;
	static function lime_cairo_stroke_extents(handle:Dynamic, x1:Float, y1:Float, x2:Float, y2:Float):Void;
	static function lime_cairo_stroke_preserve(handle:Dynamic):Void;
	static function lime_cairo_surface_flush(surface:Dynamic):Void;
	static function lime_cairo_text_path(handle:Dynamic, text:String):Void;
	static function lime_cairo_transform(handle:Dynamic, matrix:Dynamic):Void;
	static function lime_cairo_translate(handle:Dynamic, x:Float, y:Float):Void;
	static function lime_cairo_version():Int;
	static function lime_cairo_version_string():String;
	static function lime_cffi_get_native_pointer(ptr:Dynamic):Float;
	static function lime_clipboard_event_manager_register(callback:Dynamic, eventObject:Dynamic):Void;
	static function lime_clipboard_get_text():Dynamic;
	static function lime_clipboard_set_text(text:String):Void;
	static function lime_curl_easy_cleanup(handle:Dynamic):Void;
	static function lime_curl_easy_duphandle(handle:Dynamic):Dynamic;
	static function lime_curl_easy_escape(curl:Dynamic, url:String, length:Int):Dynamic;
	static function lime_curl_easy_flush(curl:Dynamic):Void;
	static function lime_curl_easy_getinfo(curl:Dynamic, info:Int):Dynamic;
	static function lime_curl_easy_init():Dynamic;
	static function lime_curl_easy_pause(handle:Dynamic, bitmask:Int):Int;
	static function lime_curl_easy_perform(easy_handle:Dynamic):Int;
	static function lime_curl_easy_recv(curl:Dynamic, buffer:Dynamic, buflen:Int, n:Int):Int;
	static function lime_curl_easy_reset(curl:Dynamic):Void;
	static function lime_curl_easy_send(curl:Dynamic, buffer:Dynamic, buflen:Int, n:Int):Int;
	static function lime_curl_easy_setopt(handle:Dynamic, option:Int, parameter:Dynamic, writeBytes:Dynamic):Int;
	static function lime_curl_easy_strerror(errornum:Int):Dynamic;
	static function lime_curl_easy_unescape(curl:Dynamic, url:String, inlength:Int, outlength:Int):Dynamic;
	static function lime_curl_getdate(date:String, now:Float):Float;
	static function lime_curl_global_cleanup():Void;
	static function lime_curl_global_init(flags:Int):Int;
	static function lime_curl_multi_add_handle(multi_handle:Dynamic, curl_object:Dynamic, curl_handle:Dynamic):Int;
	static function lime_curl_multi_get_running_handles(multi_handle:Dynamic):Int;
	static function lime_curl_multi_info_read(multi_handle:Dynamic):Dynamic;
	static function lime_curl_multi_init():Dynamic;
	static function lime_curl_multi_perform(multi_handle:Dynamic):Int;
	static function lime_curl_multi_remove_handle(multi_handle:Dynamic, curl_handle:Dynamic):Int;
	static function lime_curl_multi_setopt(multi_handle:Dynamic, option:Int, parameter:Dynamic):Int;
	static function lime_curl_multi_wait(multi_handle:Dynamic, timeout_ms:Int):Int;
	static function lime_curl_version():Dynamic;
	static function lime_curl_version_info(type:Int):Dynamic;
	static function lime_data_pointer_offset(dataPointer:Dynamic, offset:Int):Float;
	static function lime_deflate_compress(data:Dynamic, bytes:Dynamic):Dynamic;
	static function lime_deflate_decompress(data:Dynamic, bytes:Dynamic):Dynamic;
	static function lime_drop_event_manager_register(callback:Dynamic, eventObject:Dynamic):Void;
	static function lime_file_dialog_open_directory(title:String, filter:String, defaultPath:String):Dynamic;
	static function lime_file_dialog_open_file(title:String, filter:String, defaultPath:String):Dynamic;
	static function lime_file_dialog_open_files(title:String, filter:String, defaultPath:String):Dynamic;
	static function lime_file_dialog_save_file(title:String, filter:String, defaultPath:String):Dynamic;
	static function lime_file_watcher_add_directory(handle:Dynamic, path:Dynamic, recursive:Bool):Dynamic;
	static function lime_file_watcher_create(callback:Dynamic):Dynamic;
	static function lime_file_watcher_remove_directory(handle:Dynamic, watchID:Dynamic):Void;
	static function lime_file_watcher_update(handle:Dynamic):Void;
	static function lime_font_get_ascender(handle:Dynamic):Int;
	static function lime_font_get_descender(handle:Dynamic):Int;
	static function lime_font_get_family_name(handle:Dynamic):Dynamic;
	static function lime_font_get_glyph_index(handle:Dynamic, character:String):Int;
	static function lime_font_get_glyph_indices(handle:Dynamic, characters:String):Dynamic;
	static function lime_font_get_glyph_metrics(handle:Dynamic, index:Int):Dynamic;
	static function lime_font_get_height(handle:Dynamic):Int;
	static function lime_font_get_num_glyphs(handle:Dynamic):Int;
	static function lime_font_get_strikethrough_position(handle:Dynamic):Int;
	static function lime_font_get_strikethrough_thickness(handle:Dynamic):Int;
	static function lime_font_get_underline_position(handle:Dynamic):Int;
	static function lime_font_get_underline_thickness(handle:Dynamic):Int;
	static function lime_font_get_units_per_em(handle:Dynamic):Int;
	static function lime_font_load(data:Dynamic):Dynamic;
	static function lime_font_load_bytes(data:Dynamic):Dynamic;
	static function lime_font_load_file(path:Dynamic):Dynamic;
	static function lime_font_outline_decompose(handle:Dynamic, size:Int):Dynamic;
	static function lime_font_outline_decompose_no_hint(handle:Dynamic, size:Int):Dynamic;
	static function lime_font_render_glyph(handle:Dynamic, index:Int, data:Dynamic):Dynamic;
	static function lime_font_render_glyph_with_flags(handle:Dynamic, index:Int, loadFlags:Int, data:Dynamic):Dynamic;
	static function lime_font_render_glyphs(handle:Dynamic, indices:Dynamic, data:Dynamic):Dynamic;
	static function lime_font_set_size(handle:Dynamic, size:Int, dpi:Int):Void;
	static function lime_gamepad_add_mappings(mappings:Dynamic):Void;
	static function lime_gamepad_event_manager_register(callback:Dynamic, eventObject:Dynamic):Void;
	static function lime_gamepad_get_device_guid(id:Int):Dynamic;
	static function lime_gamepad_get_device_name(id:Int):Dynamic;
	static function lime_gamepad_rumble(id:Int, lowFrequencyRumble:Float, highFrequencyRumble:Float, duration:Int):Void;
	static function lime_gl_active_texture(texture:Int):Void;
	static function lime_gl_attach_shader(program:Int, shader:Int):Void;
	static function lime_gl_begin_query(target:Int, query:Int):Void;
	static function lime_gl_begin_transform_feedback(primitiveNode:Int):Void;
	static function lime_gl_bind_attrib_location(program:Int, index:Int, name:String):Void;
	static function lime_gl_bind_buffer(target:Int, buffer:Int):Void;
	static function lime_gl_bind_buffer_base(target:Int, index:Int, buffer:Int):Void;
	static function lime_gl_bind_buffer_range(target:Int, index:Int, buffer:Int, offset:Dynamic, size:Int):Void;
	static function lime_gl_bind_framebuffer(target:Int, framebuffer:Int):Void;
	static function lime_gl_bind_renderbuffer(target:Int, renderbuffer:Int):Void;
	static function lime_gl_bind_sampler(target:Int, sampler:Int):Void;
	static function lime_gl_bind_texture(target:Int, texture:Int):Void;
	static function lime_gl_bind_transform_feedback(target:Int, transformFeedback:Int):Void;
	static function lime_gl_bind_vertex_array(vertexArray:Int):Void;
	static function lime_gl_blend_color(red:Float, green:Float, blue:Float, alpha:Float):Void;
	static function lime_gl_blend_equation(mode:Int):Void;
	static function lime_gl_blend_equation_separate(modeRGB:Int, modeAlpha:Int):Void;
	static function lime_gl_blend_func(sfactor:Int, dfactor:Int):Void;
	static function lime_gl_blend_func_separate(srcRGB:Int, dstRGB:Int, srcAlpha:Int, dstAlpha:Int):Void;
	static function lime_gl_blit_framebuffer(srcX0:Int, srcY0:Int, srcX1:Int, srcY1:Int, dstX0:Int, dstY0:Int, dstX1:Int, dstY1:Int, mask:Int, filter:Int):Void;
	static function lime_gl_buffer_data(target:Int, size:Int, srcData:Dynamic, usage:Int):Void;
	static function lime_gl_buffer_sub_data(target:Int, offset:Int, size:Int, srcData:Dynamic):Void;
	static function lime_gl_check_framebuffer_status(target:Int):Int;
	static function lime_gl_clear(mask:Int):Void;
	static function lime_gl_clear_bufferfi(buffer:Int, drawBuffer:Int, depth:Float, stencil:Int):Void;
	static function lime_gl_clear_bufferfv(buffer:Int, drawBuffer:Int, data:Dynamic):Void;
	static function lime_gl_clear_bufferiv(buffer:Int, drawBuffer:Int, data:Dynamic):Void;
	static function lime_gl_clear_bufferuiv(buffer:Int, drawBuffer:Int, data:Dynamic):Void;
	static function lime_gl_clear_color(red:Float, green:Float, blue:Float, alpha:Float):Void;
	static function lime_gl_clear_depthf(depth:Float):Void;
	static function lime_gl_clear_stencil(s:Int):Void;
	static function lime_gl_client_wait_sync(sync:Dynamic, flags:Int, timeoutA:Int, timeoutB:Int):Int;
	static function lime_gl_color_mask(red:Bool, green:Bool, blue:Bool, alpha:Bool):Void;
	static function lime_gl_compile_shader(shader:Int):Void;
	static function lime_gl_compressed_tex_image_2d(target:Int, level:Int, internalformat:Int, width:Int, height:Int, border:Int, imageSize:Int, data:Dynamic):Void;
	static function lime_gl_compressed_tex_image_3d(target:Int, level:Int, internalformat:Int, width:Int, height:Int, depth:Int, border:Int, imageSize:Int, data:Dynamic):Void;
	static function lime_gl_compressed_tex_sub_image_2d(target:Int, level:Int, xoffset:Int, yoffset:Int, width:Int, height:Int, format:Int, imageSize:Int, data:Dynamic):Void;
	static function lime_gl_compressed_tex_sub_image_3d(target:Int, level:Int, xoffset:Int, yoffset:Int, zoffset:Int, width:Int, height:Int, depth:Int, format:Int, imageSize:Int, data:Dynamic):Void;
	static function lime_gl_copy_buffer_sub_data(readTarget:Int, writeTarget:Int, readOffset:Dynamic, writeOffset:Dynamic, size:Int):Void;
	static function lime_gl_copy_tex_image_2d(target:Int, level:Int, internalformat:Int, x:Int, y:Int, width:Int, height:Int, border:Int):Void;
	static function lime_gl_copy_tex_sub_image_2d(target:Int, level:Int, xoffset:Int, yoffset:Int, x:Int, y:Int, width:Int, height:Int):Void;
	static function lime_gl_copy_tex_sub_image_3d(target:Int, level:Int, xoffset:Int, yoffset:Int, zoffset:Int, x:Int, y:Int, width:Int, height:Int):Void;
	static function lime_gl_create_buffer():Int;
	static function lime_gl_create_framebuffer():Int;
	static function lime_gl_create_program():Int;
	static function lime_gl_create_query():Int;
	static function lime_gl_create_renderbuffer():Int;
	static function lime_gl_create_sampler():Int;
	static function lime_gl_create_shader(type:Int):Int;
	static function lime_gl_create_texture():Int;
	static function lime_gl_create_transform_feedback():Int;
	static function lime_gl_create_vertex_array():Int;
	static function lime_gl_cull_face(mode:Int):Void;
	static function lime_gl_delete_buffer(buffer:Int):Void;
	static function lime_gl_delete_framebuffer(framebuffer:Int):Void;
	static function lime_gl_delete_program(program:Int):Void;
	static function lime_gl_delete_query(query:Int):Void;
	static function lime_gl_delete_renderbuffer(renderbuffer:Int):Void;
	static function lime_gl_delete_sampler(sampler:Int):Void;
	static function lime_gl_delete_shader(shader:Int):Void;
	static function lime_gl_delete_sync(sync:Dynamic):Void;
	static function lime_gl_delete_texture(texture:Int):Void;
	static function lime_gl_delete_transform_feedback(transformFeedback:Int):Void;
	static function lime_gl_delete_vertex_array(vertexArray:Int):Void;
	static function lime_gl_depth_func(func:Int):Void;
	static function lime_gl_depth_mask(flag:Bool):Void;
	static function lime_gl_depth_rangef(zNear:Float, zFar:Float):Void;
	static function lime_gl_detach_shader(program:Int, shader:Int):Void;
	static function lime_gl_disable(cap:Int):Void;
	static function lime_gl_disable_vertex_attrib_array(index:Int):Void;
	static function lime_gl_draw_arrays(mode:Int, first:Int, count:Int):Void;
	static function lime_gl_draw_arrays_instanced(mode:Int, first:Int, count:Int, instanceCount:Int):Void;
	static function lime_gl_draw_buffers(buffers:Dynamic):Void;
	static function lime_gl_draw_elements(mode:Int, count:Int, type:Int, offset:Dynamic):Void;
	static function lime_gl_draw_elements_instanced(mode:Int, count:Int, type:Int, offset:Dynamic, instanceCount:Int):Void;
	static function lime_gl_draw_range_elements(mode:Int, start:Int, end:Int, count:Int, type:Int, offset:Dynamic):Void;
	static function lime_gl_enable(cap:Int):Void;
	static function lime_gl_enable_vertex_attrib_array(index:Int):Void;
	static function lime_gl_end_query(target:Int):Void;
	static function lime_gl_end_transform_feedback():Void;
	static function lime_gl_fence_sync(condition:Int, flags:Int):Dynamic;
	static function lime_gl_finish():Void;
	static function lime_gl_flush():Void;
	static function lime_gl_framebuffer_renderbuffer(target:Int, attachment:Int, renderbuffertarget:Int, renderbuffer:Int):Void;
	static function lime_gl_framebuffer_texture2D(target:Int, attachment:Int, textarget:Int, texture:Int, level:Int):Void;
	static function lime_gl_framebuffer_texture_layer(target:Int, attachment:Int, texture:Int, level:Int, layer:Int):Void;
	static function lime_gl_front_face(mode:Int):Void;
	static function lime_gl_generate_mipmap(target:Int):Void;
	static function lime_gl_get_active_attrib(program:Int, index:Int):Dynamic;
	static function lime_gl_get_active_uniform(program:Int, index:Int):Dynamic;
	static function lime_gl_get_active_uniform_block_name(program:Int, uniformBlockIndex:Int):Dynamic;
	static function lime_gl_get_active_uniform_blocki(program:Int, uniformBlockIndex:Int, pname:Int):Int;
	static function lime_gl_get_active_uniform_blockiv(program:Int, uniformBlockIndex:Int, pname:Int, params:Dynamic):Void;
	static function lime_gl_get_active_uniformsiv(program:Int, uniformIndices:Dynamic, pname:Int, params:Dynamic):Void;
	static function lime_gl_get_attached_shaders(program:Int):Dynamic;
	static function lime_gl_get_attrib_location(program:Int, name:String):Int;
	static function lime_gl_get_boolean(pname:Int):Bool;
	static function lime_gl_get_booleanv(pname:Int, params:Dynamic):Void;
	static function lime_gl_get_buffer_parameteri(target:Int, pname:Int):Int;
	static function lime_gl_get_buffer_parameteri64v(target:Int, index:Int, params:Dynamic):Void;
	static function lime_gl_get_buffer_parameteriv(target:Int, pname:Int, params:Dynamic):Void;
	static function lime_gl_get_buffer_pointerv(target:Int, pname:Int):Dynamic;
	static function lime_gl_get_buffer_sub_data(target:Int, offset:Dynamic, size:Int, data:Dynamic):Void;
	static function lime_gl_get_context_attributes():Dynamic;
	static function lime_gl_get_error():Int;
	static function lime_gl_get_extension(name:String):Dynamic;
	static function lime_gl_get_float(pname:Int):Float;
	static function lime_gl_get_floatv(pname:Int, params:Dynamic):Void;
	static function lime_gl_get_frag_data_location(program:Int, name:String):Int;
	static function lime_gl_get_framebuffer_attachment_parameteri(target:Int, attachment:Int, pname:Int):Int;
	static function lime_gl_get_framebuffer_attachment_parameteriv(target:Int, attachment:Int, pname:Int, params:Dynamic):Void;
	static function lime_gl_get_integer(pname:Int):Int;
	static function lime_gl_get_integer64i_v(pname:Int, index:Int, params:Dynamic):Void;
	static function lime_gl_get_integer64v(pname:Int, params:Dynamic):Void;
	static function lime_gl_get_integeri_v(pname:Int, index:Int, params:Dynamic):Void;
	static function lime_gl_get_integerv(pname:Int, params:Dynamic):Void;
	static function lime_gl_get_internalformativ(target:Int, internalformat:Int, pname:Int, bufSize:Int, params:Dynamic):Void;
	static function lime_gl_get_program_binary(program:Int, binaryFormat:Int, bytes:Dynamic):Void;
	static function lime_gl_get_program_info_log(program:Int):Dynamic;
	static function lime_gl_get_programi(program:Int, pname:Int):Int;
	static function lime_gl_get_programiv(program:Int, pname:Int, params:Dynamic):Void;
	static function lime_gl_get_query_objectui(target:Int, pname:Int):Int;
	static function lime_gl_get_query_objectuiv(target:Int, pname:Int, params:Dynamic):Void;
	static function lime_gl_get_queryi(target:Int, pname:Int):Int;
	static function lime_gl_get_queryiv(target:Int, pname:Int, params:Dynamic):Void;
	static function lime_gl_get_renderbuffer_parameteri(target:Int, pname:Int):Int;
	static function lime_gl_get_renderbuffer_parameteriv(target:Int, pname:Int, params:Dynamic):Void;
	static function lime_gl_get_sampler_parameterf(target:Int, pname:Int):Float;
	static function lime_gl_get_sampler_parameterfv(target:Int, pname:Int, params:Dynamic):Void;
	static function lime_gl_get_sampler_parameteri(target:Int, pname:Int):Int;
	static function lime_gl_get_sampler_parameteriv(target:Int, pname:Int, params:Dynamic):Void;
	static function lime_gl_get_shader_info_log(shader:Int):Dynamic;
	static function lime_gl_get_shader_precision_format(shadertype:Int, precisiontype:Int):Dynamic;
	static function lime_gl_get_shader_source(shader:Int):Dynamic;
	static function lime_gl_get_shaderi(shader:Int, pname:Int):Int;
	static function lime_gl_get_shaderiv(shader:Int, pname:Int, params:Dynamic):Void;
	static function lime_gl_get_string(pname:Int):Dynamic;
	static function lime_gl_get_stringi(pname:Int, index:Int):Dynamic;
	static function lime_gl_get_sync_parameteri(sync:Dynamic, pname:Int):Int;
	static function lime_gl_get_sync_parameteriv(sync:Dynamic, pname:Int, params:Dynamic):Void;
	static function lime_gl_get_tex_parameterf(target:Int, pname:Int):Float;
	static function lime_gl_get_tex_parameterfv(target:Int, pname:Int, params:Dynamic):Void;
	static function lime_gl_get_tex_parameteri(target:Int, pname:Int):Int;
	static function lime_gl_get_tex_parameteriv(target:Int, pname:Int, params:Dynamic):Void;
	static function lime_gl_get_transform_feedback_varying(program:Int, index:Int):Dynamic;
	static function lime_gl_get_uniform_block_index(program:Int, uniformBlockName:String):Int;
	static function lime_gl_get_uniform_location(program:Int, name:String):Int;
	static function lime_gl_get_uniformf(program:Int, location:Int):Float;
	static function lime_gl_get_uniformfv(program:Int, location:Int, params:Dynamic):Void;
	static function lime_gl_get_uniformi(program:Int, location:Int):Int;
	static function lime_gl_get_uniformiv(program:Int, location:Int, params:Dynamic):Void;
	static function lime_gl_get_uniformui(program:Int, location:Int):Int;
	static function lime_gl_get_uniformuiv(program:Int, location:Int, params:Dynamic):Void;
	static function lime_gl_get_vertex_attrib_pointerv(index:Int, pname:Int):Dynamic;
	static function lime_gl_get_vertex_attribf(index:Int, pname:Int):Float;
	static function lime_gl_get_vertex_attribfv(index:Int, pname:Int, params:Dynamic):Void;
	static function lime_gl_get_vertex_attribi(index:Int, pname:Int):Int;
	static function lime_gl_get_vertex_attribii(index:Int, pname:Int):Int;
	static function lime_gl_get_vertex_attribiiv(index:Int, pname:Int, params:Dynamic):Void;
	static function lime_gl_get_vertex_attribiui(index:Int, pname:Int):Int;
	static function lime_gl_get_vertex_attribiuiv(index:Int, pname:Int, params:Dynamic):Void;
	static function lime_gl_get_vertex_attribiv(index:Int, pname:Int, params:Dynamic):Void;
	static function lime_gl_hint(target:Int, mode:Int):Void;
	static function lime_gl_invalidate_framebuffer(target:Int, attachments:Dynamic):Void;
	static function lime_gl_invalidate_sub_framebuffer(target:Int, attachments:Dynamic, x:Int, y:Int, width:Int, height:Int):Void;
	static function lime_gl_is_buffer(buffer:Int):Bool;
	static function lime_gl_is_enabled(cap:Int):Bool;
	static function lime_gl_is_framebuffer(framebuffer:Int):Bool;
	static function lime_gl_is_program(program:Int):Bool;
	static function lime_gl_is_query(query:Int):Bool;
	static function lime_gl_is_renderbuffer(renderbuffer:Int):Bool;
	static function lime_gl_is_sampler(sampler:Int):Bool;
	static function lime_gl_is_shader(shader:Int):Bool;
	static function lime_gl_is_sync(sync:Dynamic):Bool;
	static function lime_gl_is_texture(texture:Int):Bool;
	static function lime_gl_is_transform_feedback(transformFeedback:Int):Bool;
	static function lime_gl_is_vertex_array(vertexArray:Int):Bool;
	static function lime_gl_line_width(width:Float):Void;
	static function lime_gl_link_program(program:Int):Void;
	static function lime_gl_map_buffer_range(target:Int, offset:Dynamic, length:Int, access:Int):Dynamic;
	static function lime_gl_object_deregister(object:Dynamic):Void;
	static function lime_gl_object_from_id(id:Int, type:Int):Dynamic;
	static function lime_gl_object_register(id:Int, type:Int, object:Dynamic):Dynamic;
	static function lime_gl_pause_transform_feedback():Void;
	static function lime_gl_pixel_storei(pname:Int, param:Int):Void;
	static function lime_gl_polygon_offset(factor:Float, units:Float):Void;
	static function lime_gl_program_binary(program:Int, binaryFormat:Int, binary:Dynamic, length:Int):Void;
	static function lime_gl_program_parameteri(program:Int, pname:Int, value:Int):Void;
	static function lime_gl_read_buffer(src:Int):Void;
	static function lime_gl_read_pixels(x:Int, y:Int, width:Int, height:Int, format:Int, type:Int, pixels:Dynamic):Void;
	static function lime_gl_release_shader_compiler():Void;
	static function lime_gl_renderbuffer_storage(target:Int, internalformat:Int, width:Int, height:Int):Void;
	static function lime_gl_renderbuffer_storage_multisample(target:Int, samples:Int, internalformat:Int, width:Int, height:Int):Void;
	static function lime_gl_resume_transform_feedback():Void;
	static function lime_gl_sample_coverage(value:Float, invert:Bool):Void;
	static function lime_gl_sampler_parameterf(sampler:Int, pname:Int, param:Float):Void;
	static function lime_gl_sampler_parameteri(sampler:Int, pname:Int, param:Int):Void;
	static function lime_gl_scissor(x:Int, y:Int, width:Int, height:Int):Void;
	static function lime_gl_shader_binary(shaders:Dynamic, binaryformat:Int, binary:Dynamic, length:Int):Void;
	static function lime_gl_shader_source(shader:Int, source:String):Void;
	static function lime_gl_stencil_func(func:Int, ref:Int, mask:Int):Void;
	static function lime_gl_stencil_func_separate(face:Int, func:Int, ref:Int, mask:Int):Void;
	static function lime_gl_stencil_mask(mask:Int):Void;
	static function lime_gl_stencil_mask_separate(face:Int, mask:Int):Void;
	static function lime_gl_stencil_op(fail:Int, zfail:Int, zpass:Int):Void;
	static function lime_gl_stencil_op_separate(face:Int, fail:Int, zfail:Int, zpass:Int):Void;
	static function lime_gl_tex_image_2d(target:Int, level:Int, internalformat:Int, width:Int, height:Int, border:Int, format:Int, type:Int, data:Dynamic):Void;
	static function lime_gl_tex_image_3d(target:Int, level:Int, internalformat:Int, width:Int, height:Int, depth:Int, border:Int, format:Int, type:Int, data:Dynamic):Void;
	static function lime_gl_tex_parameterf(target:Int, pname:Int, param:Float):Void;
	static function lime_gl_tex_parameteri(target:Int, pname:Int, param:Int):Void;
	static function lime_gl_tex_storage_2d(target:Int, level:Int, internalformat:Int, width:Int, height:Int):Void;
	static function lime_gl_tex_storage_3d(target:Int, level:Int, internalformat:Int, width:Int, height:Int, depth:Int):Void;
	static function lime_gl_tex_sub_image_2d(target:Int, level:Int, xoffset:Int, yoffset:Int, width:Int, height:Int, format:Int, type:Int, data:Dynamic):Void;
	static function lime_gl_tex_sub_image_3d(target:Int, level:Int, xoffset:Int, yoffset:Int, zoffset:Int, width:Int, height:Int, depth:Int, format:Int, type:Int, data:Dynamic):Void;
	static function lime_gl_transform_feedback_varyings(program:Int, varyings:Dynamic, bufferMode:Int):Void;
	static function lime_gl_uniform1f(location:Int, v0:Float):Void;
	static function lime_gl_uniform1fv(location:Int, count:Int, v:Dynamic):Void;
	static function lime_gl_uniform1i(location:Int, v0:Int):Void;
	static function lime_gl_uniform1iv(location:Int, count:Int, v:Dynamic):Void;
	static function lime_gl_uniform1ui(location:Int, v0:Int):Void;
	static function lime_gl_uniform1uiv(location:Int, count:Int, v:Dynamic):Void;
	static function lime_gl_uniform2f(location:Int, v0:Float, v1:Float):Void;
	static function lime_gl_uniform2fv(location:Int, count:Int, v:Dynamic):Void;
	static function lime_gl_uniform2i(location:Int, v0:Int, v1:Int):Void;
	static function lime_gl_uniform2iv(location:Int, count:Int, v:Dynamic):Void;
	static function lime_gl_uniform2ui(location:Int, v0:Int, v1:Int):Void;
	static function lime_gl_uniform2uiv(location:Int, count:Int, v:Dynamic):Void;
	static function lime_gl_uniform3f(location:Int, v0:Float, v1:Float, v2:Float):Void;
	static function lime_gl_uniform3fv(location:Int, count:Int, v:Dynamic):Void;
	static function lime_gl_uniform3i(location:Int, v0:Int, v1:Int, v2:Int):Void;
	static function lime_gl_uniform3iv(location:Int, count:Int, v:Dynamic):Void;
	static function lime_gl_uniform3ui(location:Int, v0:Int, v1:Int, v2:Int):Void;
	static function lime_gl_uniform3uiv(location:Int, count:Int, v:Dynamic):Void;
	static function lime_gl_uniform4f(location:Int, v0:Float, v1:Float, v2:Float, v3:Float):Void;
	static function lime_gl_uniform4fv(location:Int, count:Int, v:Dynamic):Void;
	static function lime_gl_uniform4i(location:Int, v0:Int, v1:Int, v2:Int, v3:Int):Void;
	static function lime_gl_uniform4iv(location:Int, count:Int, v:Dynamic):Void;
	static function lime_gl_uniform4ui(location:Int, v0:Int, v1:Int, v2:Int, v3:Int):Void;
	static function lime_gl_uniform4uiv(location:Int, count:Int, v:Dynamic):Void;
	static function lime_gl_uniform_block_binding(program:Int, uniformBlockIndex:Int, uniformBlockBinding:Int):Void;
	static function lime_gl_uniform_matrix2fv(location:Int, count:Int, transpose:Bool, value:Dynamic):Void;
	static function lime_gl_uniform_matrix2x3fv(location:Int, count:Int, transpose:Bool, value:Dynamic):Void;
	static function lime_gl_uniform_matrix2x4fv(location:Int, count:Int, transpose:Bool, value:Dynamic):Void;
	static function lime_gl_uniform_matrix3fv(location:Int, count:Int, transpose:Bool, value:Dynamic):Void;
	static function lime_gl_uniform_matrix3x2fv(location:Int, count:Int, transpose:Bool, value:Dynamic):Void;
	static function lime_gl_uniform_matrix3x4fv(location:Int, count:Int, transpose:Bool, value:Dynamic):Void;
	static function lime_gl_uniform_matrix4fv(location:Int, count:Int, transpose:Bool, value:Dynamic):Void;
	static function lime_gl_uniform_matrix4x2fv(location:Int, count:Int, transpose:Bool, value:Dynamic):Void;
	static function lime_gl_uniform_matrix4x3fv(location:Int, count:Int, transpose:Bool, value:Dynamic):Void;
	static function lime_gl_unmap_buffer(target:Int):Bool;
	static function lime_gl_use_program(program:Int):Void;
	static function lime_gl_validate_program(program:Int):Void;
	static function lime_gl_vertex_attrib1f(indx:Int, v0:Float):Void;
	static function lime_gl_vertex_attrib1fv(indx:Int, values:Dynamic):Void;
	static function lime_gl_vertex_attrib2f(indx:Int, v0:Float, v1:Float):Void;
	static function lime_gl_vertex_attrib2fv(indx:Int, values:Dynamic):Void;
	static function lime_gl_vertex_attrib3f(indx:Int, v0:Float, v1:Float, v2:Float):Void;
	static function lime_gl_vertex_attrib3fv(indx:Int, values:Dynamic):Void;
	static function lime_gl_vertex_attrib4f(indx:Int, v0:Float, v1:Float, v2:Float, v3:Float):Void;
	static function lime_gl_vertex_attrib4fv(indx:Int, values:Dynamic):Void;
	static function lime_gl_vertex_attrib_divisor(indx:Int, divisor:Int):Void;
	static function lime_gl_vertex_attrib_ipointer(indx:Int, size:Int, type:Int, stride:Int, offset:Dynamic):Void;
	static function lime_gl_vertex_attrib_pointer(indx:Int, size:Int, type:Int, normalized:Bool, stride:Int, offset:Dynamic):Void;
	static function lime_gl_vertex_attribi4i(indx:Int, v0:Int, v1:Int, v2:Int, v3:Int):Void;
	static function lime_gl_vertex_attribi4iv(indx:Int, values:Dynamic):Void;
	static function lime_gl_vertex_attribi4ui(indx:Int, v0:Int, v1:Int, v2:Int, v3:Int):Void;
	static function lime_gl_vertex_attribi4uiv(indx:Int, values:Dynamic):Void;
	static function lime_gl_viewport(x:Int, y:Int, width:Int, height:Int):Void;
	static function lime_gl_wait_sync(sync:Dynamic, flags:Int, timeoutA:Int, timeoutB:Int):Void;
	static function lime_gzip_compress(data:Dynamic, bytes:Dynamic):Dynamic;
	static function lime_gzip_decompress(data:Dynamic, bytes:Dynamic):Dynamic;
	static function lime_haptic_vibrate(period:Int, duration:Int):Void;
	static function lime_hb_blob_create(data:Dynamic, length:Int, memoryMode:Int):Dynamic;
	static function lime_hb_blob_create_sub_blob(parent:Dynamic, offset:Int, length:Int):Dynamic;
	static function lime_hb_blob_get_data(blob:Dynamic):Float;
	static function lime_hb_blob_get_data_writable(blob:Dynamic):Float;
	static function lime_hb_blob_get_empty():Dynamic;
	static function lime_hb_blob_get_length(blob:Dynamic):Int;
	static function lime_hb_blob_is_immutable(blob:Dynamic):Bool;
	static function lime_hb_blob_make_immutable(blob:Dynamic):Void;
	static function lime_hb_buffer_add(buffer:Dynamic, codepoint:Int, cluster:Int):Void;
	static function lime_hb_buffer_add_codepoints(buffer:Dynamic, text:Dynamic, textLength:Int, itemOffset:Int, itemLength:Int):Void;
	static function lime_hb_buffer_add_hxstring(buffer:Dynamic, text:String, itemOffset:Int, itemLength:Int):Void;
	static function lime_hb_buffer_add_utf16(buffer:Dynamic, text:Dynamic, textLength:Int, itemOffset:Int, itemLength:Int):Void;
	static function lime_hb_buffer_add_utf32(buffer:Dynamic, text:Dynamic, textLength:Int, itemOffset:Int, itemLength:Int):Void;
	static function lime_hb_buffer_add_utf8(buffer:Dynamic, text:String, itemOffset:Int, itemLength:Int):Void;
	static function lime_hb_buffer_allocation_successful(buffer:Dynamic):Bool;
	static function lime_hb_buffer_clear_contents(buffer:Dynamic):Void;
	static function lime_hb_buffer_create():Dynamic;
	static function lime_hb_buffer_get_cluster_level(buffer:Dynamic):Int;
	static function lime_hb_buffer_get_content_type(buffer:Dynamic):Int;
	static function lime_hb_buffer_get_direction(buffer:Dynamic):Int;
	static function lime_hb_buffer_get_empty():Dynamic;
	static function lime_hb_buffer_get_flags(buffer:Dynamic):Int;
	static function lime_hb_buffer_get_glyph_infos(buffer:Dynamic, bytes:Dynamic):Dynamic;
	static function lime_hb_buffer_get_glyph_positions(buffer:Dynamic, bytes:Dynamic):Dynamic;
	static function lime_hb_buffer_get_language(buffer:Dynamic):Dynamic;
	static function lime_hb_buffer_get_length(buffer:Dynamic):Int;
	static function lime_hb_buffer_get_replacement_codepoint(buffer:Dynamic):Int;
	static function lime_hb_buffer_get_script(buffer:Dynamic):Int;
	static function lime_hb_buffer_get_segment_properties(buffer:Dynamic, props:Dynamic):Void;
	static function lime_hb_buffer_guess_segment_properties(buffer:Dynamic):Void;
	static function lime_hb_buffer_normalize_glyphs(buffer:Dynamic):Void;
	static function lime_hb_buffer_preallocate(buffer:Dynamic, size:Int):Bool;
	static function lime_hb_buffer_reset(buffer:Dynamic):Void;
	static function lime_hb_buffer_reverse(buffer:Dynamic):Void;
	static function lime_hb_buffer_reverse_clusters(buffer:Dynamic):Void;
	static function lime_hb_buffer_serialize_format_from_string(str:String):Int;
	static function lime_hb_buffer_serialize_format_to_string(format:Int):Dynamic;
	static function lime_hb_buffer_serialize_list_formats():Dynamic;
	static function lime_hb_buffer_set_cluster_level(buffer:Dynamic, clusterLevel:Int):Void;
	static function lime_hb_buffer_set_content_type(buffer:Dynamic, contentType:Int):Void;
	static function lime_hb_buffer_set_direction(buffer:Dynamic, direction:Int):Void;
	static function lime_hb_buffer_set_flags(buffer:Dynamic, flags:Int):Void;
	static function lime_hb_buffer_set_language(buffer:Dynamic, language:Dynamic):Void;
	static function lime_hb_buffer_set_length(buffer:Dynamic, length:Int):Bool;
	static function lime_hb_buffer_set_replacement_codepoint(buffer:Dynamic, replacement:Int):Void;
	static function lime_hb_buffer_set_script(buffer:Dynamic, script:Int):Void;
	static function lime_hb_buffer_set_segment_properties(buffer:Dynamic, props:Dynamic):Void;
	static function lime_hb_face_create(blob:Dynamic, index:Int):Dynamic;
	static function lime_hb_face_get_empty():Dynamic;
	static function lime_hb_face_get_glyph_count(face:Dynamic):Int;
	static function lime_hb_face_get_index(face:Dynamic):Int;
	static function lime_hb_face_get_upem(face:Dynamic):Int;
	static function lime_hb_face_is_immutable(face:Dynamic):Bool;
	static function lime_hb_face_make_immutable(face:Dynamic):Void;
	static function lime_hb_face_reference_blob(face:Dynamic):Dynamic;
	static function lime_hb_face_reference_table(face:Dynamic, tag:Int):Dynamic;
	static function lime_hb_face_set_glyph_count(face:Dynamic, glyphCount:Int):Void;
	static function lime_hb_face_set_index(face:Dynamic, index:Int):Void;
	static function lime_hb_face_set_upem(face:Dynamic, upem:Int):Void;
	static function lime_hb_feature_from_string(str:String):Dynamic;
	static function lime_hb_feature_to_string(feature:Dynamic):Dynamic;
	static function lime_hb_font_add_glyph_origin_for_direction(font:Dynamic, glyph:Int, direction:Int, x:Int, y:Int):Void;
	static function lime_hb_font_create(face:Dynamic):Dynamic;
	static function lime_hb_font_create_sub_font(parent:Dynamic):Dynamic;
	static function lime_hb_font_get_empty():Dynamic;
	static function lime_hb_font_get_face(font:Dynamic):Dynamic;
	static function lime_hb_font_get_glyph_advance_for_direction(font:Dynamic, glyph:Int, direction:Int):Dynamic;
	static function lime_hb_font_get_glyph_kerning_for_direction(font:Dynamic, firstGlyph:Int, secondGlyph:Int, direction:Int):Dynamic;
	static function lime_hb_font_get_glyph_origin_for_direction(font:Dynamic, glyph:Int, direction:Int):Dynamic;
	static function lime_hb_font_get_parent(font:Dynamic):Dynamic;
	static function lime_hb_font_get_ppem(font:Dynamic):Dynamic;
	static function lime_hb_font_get_scale(font:Dynamic):Dynamic;
	static function lime_hb_font_glyph_from_string(font:Dynamic, s:String):Int;
	static function lime_hb_font_glyph_to_string(font:Dynamic, codepoint:Int):Dynamic;
	static function lime_hb_font_is_immutable(font:Dynamic):Bool;
	static function lime_hb_font_make_immutable(font:Dynamic):Void;
	static function lime_hb_font_set_ppem(font:Dynamic, xppem:Int, yppem:Int):Void;
	static function lime_hb_font_set_scale(font:Dynamic, xScale:Int, yScale:Int):Void;
	static function lime_hb_font_subtract_glyph_origin_for_direction(font:Dynamic, glyph:Int, direction:Int, x:Int, y:Int):Void;
	static function lime_hb_ft_font_changed(font:Dynamic):Void;
	static function lime_hb_ft_font_create(font:Dynamic):Dynamic;
	static function lime_hb_ft_font_create_referenced(font:Dynamic):Dynamic;
	static function lime_hb_ft_font_get_load_flags(font:Dynamic):Int;
	static function lime_hb_ft_font_set_load_flags(font:Dynamic, loadFlags:Int):Void;
	static function lime_hb_language_from_string(str:String):Dynamic;
	static function lime_hb_language_get_default():Dynamic;
	static function lime_hb_language_to_string(language:Dynamic):Dynamic;
	static function lime_hb_segment_properties_equal(a:Dynamic, b:Dynamic):Bool;
	static function lime_hb_segment_properties_hash(p:Dynamic):Int;
	static function lime_hb_set_add(set:Dynamic, codepoint:Int):Void;
	static function lime_hb_set_add_range(set:Dynamic, first:Int, last:Int):Void;
	static function lime_hb_set_allocation_successful(set:Dynamic):Bool;
	static function lime_hb_set_clear(set:Dynamic):Void;
	static function lime_hb_set_create():Dynamic;
	static function lime_hb_set_del(set:Dynamic, codepoint:Int):Void;
	static function lime_hb_set_del_range(set:Dynamic, first:Int, last:Int):Void;
	static function lime_hb_set_get_empty():Dynamic;
	static function lime_hb_set_get_max(set:Dynamic):Int;
	static function lime_hb_set_get_min(set:Dynamic):Int;
	static function lime_hb_set_get_population(set:Dynamic):Int;
	static function lime_hb_set_has(set:Dynamic, codepoint:Int):Bool;
	static function lime_hb_set_intersect(set:Dynamic, other:Dynamic):Void;
	static function lime_hb_set_invert(set:Dynamic):Void;
	static function lime_hb_set_is_empty(set:Dynamic):Bool;
	static function lime_hb_set_is_equal(set:Dynamic, other:Dynamic):Bool;
	static function lime_hb_set_next(set:Dynamic):Int;
	static function lime_hb_set_next_range(set:Dynamic):Dynamic;
	static function lime_hb_set_set(set:Dynamic, other:Dynamic):Void;
	static function lime_hb_set_subtract(set:Dynamic, other:Dynamic):Void;
	static function lime_hb_set_symmetric_difference(set:Dynamic, other:Dynamic):Void;
	static function lime_hb_set_union(set:Dynamic, other:Dynamic):Void;
	static function lime_hb_shape(font:Dynamic, buffer:Dynamic, features:Dynamic):Void;
	static function lime_image_data_util_color_transform(image:Dynamic, rect:Dynamic, colorMatrix:Dynamic):Void;
	static function lime_image_data_util_copy_channel(image:Dynamic, sourceImage:Dynamic, sourceRect:Dynamic, destPoint:Dynamic, srcChannel:Int, destChannel:Int):Void;
	static function lime_image_data_util_copy_pixels(image:Dynamic, sourceImage:Dynamic, sourceRect:Dynamic, destPoint:Dynamic, alphaImage:Dynamic, alphaPoint:Dynamic, mergeAlpha:Bool):Void;
	static function lime_image_data_util_fill_rect(image:Dynamic, rect:Dynamic, rg:Int, ba:Int):Void;
	static function lime_image_data_util_flood_fill(image:Dynamic, x:Int, y:Int, rg:Int, ba:Int):Void;
	static function lime_image_data_util_get_pixels(image:Dynamic, rect:Dynamic, format:Int, bytes:Dynamic):Void;
	static function lime_image_data_util_merge(image:Dynamic, sourceImage:Dynamic, sourceRect:Dynamic, destPoint:Dynamic, redMultiplier:Int, greenMultiplier:Int, blueMultiplier:Int, alphaMultiplier:Int):Void;
	static function lime_image_data_util_multiply_alpha(image:Dynamic):Void;
	static function lime_image_data_util_resize(image:Dynamic, buffer:Dynamic, width:Int, height:Int):Void;
	static function lime_image_data_util_set_format(image:Dynamic, format:Int):Void;
	static function lime_image_data_util_set_pixels(image:Dynamic, rect:Dynamic, bytes:Dynamic, offset:Int, format:Int, endian:Int):Void;
	static function lime_image_data_util_threshold(image:Dynamic, sourceImage:Dynamic, sourceRect:Dynamic, destPoint:Dynamic, operation:Int, thresholdRG:Int, thresholdBA:Int, colorRG:Int, colorBA:Int, maskRG:Int, maskBA:Int, copySource:Bool):Int;
	static function lime_image_data_util_unmultiply_alpha(image:Dynamic):Void;
	static function lime_image_encode(data:Dynamic, type:Int, quality:Int, bytes:Dynamic):Dynamic;
	static function lime_image_load(data:Dynamic, buffer:Dynamic):Dynamic;
	static function lime_image_load_bytes(data:Dynamic, buffer:Dynamic):Dynamic;
	static function lime_image_load_file(path:Dynamic, buffer:Dynamic):Dynamic;
	static function lime_jvm_audio_decode(data:haxe.io.BytesData, outInfo:java.NativeArray<Int>):haxe.io.BytesData;
	static function lime_jni_call_member(jniMethod:Dynamic, jniObject:Dynamic, args:Dynamic):Dynamic;
	static function lime_jni_call_static(jniMethod:Dynamic, args:Dynamic):Dynamic;
	static function lime_jni_create_field(className:String, field:String, signature:String, isStatic:Bool):Dynamic;
	static function lime_jni_create_method(className:String, method:String, signature:String, isStatic:Bool, quiet:Bool):Dynamic;
	static function lime_jni_get_env():Float;
	static function lime_jni_get_member(jniField:Dynamic, jniObject:Dynamic):Dynamic;
	static function lime_jni_get_static(jniField:Dynamic):Dynamic;
	static function lime_jni_post_ui_callback(callback:Dynamic):Void;
	static function lime_jni_set_member(jniField:Dynamic, jniObject:Dynamic, value:Dynamic):Void;
	static function lime_jni_set_static(jniField:Dynamic, value:Dynamic):Void;
	static function lime_joystick_event_manager_register(callback:Dynamic, eventObject:Dynamic):Void;
	static function lime_joystick_get_device_guid(id:Int):Dynamic;
	static function lime_joystick_get_device_name(id:Int):Dynamic;
	static function lime_joystick_get_num_axes(id:Int):Int;
	static function lime_joystick_get_num_buttons(id:Int):Int;
	static function lime_joystick_get_num_hats(id:Int):Int;
	static function lime_jpeg_decode_bytes(data:Dynamic, decodeData:Bool, buffer:Dynamic):Dynamic;
	static function lime_jpeg_decode_file(path:String, decodeData:Bool, buffer:Dynamic):Dynamic;
	static function lime_key_code_from_scan_code(scanCode:Int):Int;
	static function lime_key_code_to_scan_code(keyCode:Int):Int;
	static function lime_key_event_manager_register(callback:Dynamic, eventObject:Dynamic):Void;
	static function lime_lzma_compress(data:Dynamic, bytes:Dynamic):Dynamic;
	static function lime_lzma_decompress(data:Dynamic, bytes:Dynamic):Dynamic;
	static function lime_mouse_event_manager_register(callback:Dynamic, eventObject:Dynamic):Void;
	static function lime_neko_execute(module:String):Void;
	static function lime_orientation_event_manager_register(callback:Dynamic, eventObject:Dynamic):Void;
	static function lime_png_decode_bytes(data:Dynamic, decodeData:Bool, buffer:Dynamic):Dynamic;
	static function lime_png_decode_file(path:String, decodeData:Bool, buffer:Dynamic):Dynamic;
	static function lime_render_event_manager_register(callback:Dynamic, eventObject:Dynamic):Void;
	static function lime_sdl_sound_get_info_from_bytes(bytes:Dynamic):Dynamic;
	static function lime_sdl_sound_get_info_from_file(path:String):Dynamic;
	static function lime_sdl_sound_stream_clear(stream:Dynamic):Void;
	static function lime_sdl_sound_stream_from_bytes(bytes:Dynamic):Dynamic;
	static function lime_sdl_sound_stream_from_file(path:String):Dynamic;
	static function lime_sdl_sound_stream_read(stream:Dynamic, buffer:Dynamic, length:Int):Int;
	static function lime_sdl_sound_stream_rewind(stream:Dynamic):Bool;
	static function lime_sdl_sound_stream_seek(stream:Dynamic, ms:Int):Bool;
	static function lime_sensor_event_manager_register(callback:Dynamic, eventObject:Dynamic):Void;
	static function lime_system_get_allow_screen_timeout():Bool;
	static function lime_system_get_device_model():Dynamic;
	static function lime_system_get_device_orientation():Int;
	static function lime_system_get_device_vendor():Dynamic;
	static function lime_system_get_directory(type:Int, company:String, title:String):Dynamic;
	static function lime_system_get_display(index:Int):Dynamic;
	static function lime_jvm_screen_width():Int;
	static function lime_jvm_screen_height():Int;
	static function lime_system_get_ios_tablet():Bool;
	static function lime_system_get_num_displays():Int;
	static function lime_system_get_platform_label():Dynamic;
	static function lime_system_get_platform_name():Dynamic;
	static function lime_system_get_platform_version():Dynamic;
	static function lime_system_get_timer():Float;
	static function lime_system_open_file(path:String):Void;
	static function lime_system_open_url(url:String, target:String):Void;
	static function lime_system_set_allow_screen_timeout(value:Bool):Bool;
	static function lime_text_event_manager_register(callback:Dynamic, eventObject:Dynamic):Void;
	static function lime_touch_event_manager_register(callback:Dynamic, eventObject:Dynamic):Void;
	static function lime_vorbis_file_bitrate(vorbisFile:Dynamic, bitstream:Int):Int;
	static function lime_vorbis_file_bitrate_instant(vorbisFile:Dynamic):Int;
	static function lime_vorbis_file_clear(vorbisFile:Dynamic):Void;
	static function lime_vorbis_file_comment(vorbisFile:Dynamic, bitstream:Int):Dynamic;
	static function lime_vorbis_file_crosslap(vorbisFile:Dynamic, otherVorbisFile:Dynamic):Dynamic;
	static function lime_vorbis_file_from_bytes(bytes:Dynamic):Dynamic;
	static function lime_vorbis_file_from_file(path:String):Dynamic;
	static function lime_vorbis_file_info(vorbisFile:Dynamic, bitstream:Int):Dynamic;
	static function lime_vorbis_file_pcm_seek(vorbisFile:Dynamic, posLow:Dynamic, posHigh:Dynamic):Int;
	static function lime_vorbis_file_pcm_seek_lap(vorbisFile:Dynamic, posLow:Dynamic, posHigh:Dynamic):Int;
	static function lime_vorbis_file_pcm_seek_page(vorbisFile:Dynamic, posLow:Dynamic, posHigh:Dynamic):Int;
	static function lime_vorbis_file_pcm_seek_page_lap(vorbisFile:Dynamic, posLow:Dynamic, posHigh:Dynamic):Int;
	static function lime_vorbis_file_pcm_tell(vorbisFile:Dynamic):Dynamic;
	static function lime_vorbis_file_pcm_total(vorbisFile:Dynamic, bitstream:Int):Dynamic;
	static function lime_vorbis_file_raw_seek(vorbisFile:Dynamic, posLow:Dynamic, posHigh:Dynamic):Int;
	static function lime_vorbis_file_raw_seek_lap(vorbisFile:Dynamic, posLow:Dynamic, posHigh:Dynamic):Int;
	static function lime_vorbis_file_raw_tell(vorbisFile:Dynamic):Dynamic;
	static function lime_vorbis_file_raw_total(vorbisFile:Dynamic, bitstream:Int):Dynamic;
	static function lime_vorbis_file_read(vorbisFile:Dynamic, buffer:Dynamic, position:Int, length:Int, bigendianp:Bool, word:Int, signed:Bool):Dynamic;
	static function lime_vorbis_file_read_float(vorbisFile:Dynamic, pcmChannels:Dynamic, samples:Int):Dynamic;
	static function lime_vorbis_file_seekable(vorbisFile:Dynamic):Bool;
	static function lime_vorbis_file_serial_number(vorbisFile:Dynamic, bitstream:Int):Int;
	static function lime_vorbis_file_streams(vorbisFile:Dynamic):Int;
	static function lime_vorbis_file_time_seek(vorbisFile:Dynamic, s:Float):Int;
	static function lime_vorbis_file_time_seek_lap(vorbisFile:Dynamic, s:Float):Int;
	static function lime_vorbis_file_time_seek_page(vorbisFile:Dynamic, s:Float):Int;
	static function lime_vorbis_file_time_seek_page_lap(vorbisFile:Dynamic, s:Float):Int;
	static function lime_vorbis_file_time_tell(vorbisFile:Dynamic):Float;
	static function lime_vorbis_file_time_total(vorbisFile:Dynamic, bitstream:Int):Float;
	static function lime_window_alert(handle:Dynamic, message:String, title:String):Void;
	static function lime_window_close(handle:Dynamic):Void;
	static function lime_window_context_flip(handle:Dynamic):Void;
	static function lime_window_context_lock(handle:Dynamic):Dynamic;
	static function lime_window_context_make_current(handle:Dynamic):Void;
	static function lime_window_context_unlock(handle:Dynamic):Void;
	static function lime_window_create(application:Dynamic, width:Int, height:Int, flags:Int, title:String):Dynamic;
	static function lime_window_event_manager_register(callback:Dynamic, eventObject:Dynamic):Void;
	static function lime_window_focus(handle:Dynamic):Void;
	static function lime_window_get_context(handle:Dynamic):Float;
	static function lime_window_get_context_type(handle:Dynamic):Dynamic;
	static function lime_window_get_display(handle:Dynamic):Int;
	static function lime_window_get_display_mode(handle:Dynamic):Dynamic;
	static function lime_window_get_height(handle:Dynamic):Int;
	static function lime_window_get_id(handle:Dynamic):Int;
	static function lime_window_get_mouse_lock(handle:Dynamic):Bool;
	static function lime_window_get_opacity(handle:Dynamic):Float;
	static function lime_window_get_scale(handle:Dynamic):Float;
	static function lime_window_get_text_input_enabled(handle:Dynamic):Bool;
	static function lime_window_get_width(handle:Dynamic):Int;
	static function lime_window_get_x(handle:Dynamic):Int;
	static function lime_window_get_y(handle:Dynamic):Int;
	static function lime_window_move(handle:Dynamic, x:Int, y:Int):Void;
	static function lime_window_read_pixels(handle:Dynamic, rect:Dynamic, imageBuffer:Dynamic):Dynamic;
	static function lime_window_resize(handle:Dynamic, width:Int, height:Int):Void;
	static function lime_window_set_always_on_top(handle:Dynamic, alwaysOnTop:Bool):Bool;
	static function lime_window_set_borderless(handle:Dynamic, borderless:Bool):Bool;
	static function lime_window_set_cursor(handle:Dynamic, cursor:Int):Void;
	static function lime_window_set_display_mode(handle:Dynamic, displayMode:Dynamic):Dynamic;
	static function lime_window_set_fullscreen(handle:Dynamic, fullscreen:Bool):Bool;
	static function lime_window_set_icon(handle:Dynamic, buffer:Dynamic):Void;
	static function lime_window_set_maximized(handle:Dynamic, maximized:Bool):Bool;
	static function lime_window_set_maximum_size(handle:Dynamic, width:Int, height:Int):Void;
	static function lime_window_set_minimized(handle:Dynamic, minimized:Bool):Bool;
	static function lime_window_set_minimum_size(handle:Dynamic, width:Int, height:Int):Void;
	static function lime_window_set_mouse_lock(handle:Dynamic, mouseLock:Bool):Void;
	static function lime_window_set_opacity(handle:Dynamic, value:Float):Void;
	static function lime_window_set_resizable(handle:Dynamic, resizable:Bool):Bool;
	static function lime_window_set_text_input_enabled(handle:Dynamic, enabled:Bool):Void;
	static function lime_window_set_text_input_rect(handle:Dynamic, rect:Dynamic):Void;
	static function lime_window_set_title(handle:Dynamic, title:String):Dynamic;
	static function lime_window_set_visible(handle:Dynamic, visible:Bool):Bool;
	static function lime_window_warp_mouse(handle:Dynamic, x:Int, y:Int):Void;
	static function lime_zlib_compress(data:Dynamic, bytes:Dynamic):Dynamic;
	static function lime_zlib_decompress(data:Dynamic, bytes:Dynamic):Dynamic;
	static function lime_reflect_log(s:String):Void;
}